from __future__ import annotations

import logging
import os
import re
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Recruitment agency exclusion
# ---------------------------------------------------------------------------
# Three layers: (1) hardcoded exact-match set below, (2) runtime YAML
# additions appended via the "agy job" button in the UI, (3) keyword
# fallback for agencies not yet in either list.

EXCLUDED_RECRUITERS: set[str] = {
    '4square recruitment ltd',
    'abacus group',
    'abbeygate search ltd',
    'acca careers',
    'additional resources ltd',
    'adele carr recruitment limited',
    'adepta partners limited',
    'adlib recruitment',
    'adsearch',
    'advanced resource managers',
    'advanced resource managers limited',
    'aimee willow connex limited',
    'akkodis',
    'albert bow',
    'allied recruitment',
    'alphaprime financial services inc',
    'alquemy',
    'altum consulting',
    'amd recruitment',
    'ampersand world',
    'ams cws',
    'anderson recruitment ltd',
    'annex consulting group',
    'anson mccade',
    'apex resources ltd',
    'apidel technologies',
    'apollo solutions',
    'appcast enterprise',
    'appcastenterprise',
    'artis recruitment',
    'ashdown group',
    'aspired careers limited',
    'astra north infoteck inc.',
    'austin rose',
    'australasian recruitment company',
    'belinda roberts ltd',
    'bell cornwall recruitment',
    'belmont lavan ltd',
    'benton partners',
    'bettingjobs',
    'birchrose associates',
    'blackfern recruitment',
    'blue pelican consulting limited',
    'bma recruitment ltd',
    'boden group',
    'bonhill partners',
    'brains workgroup, inc.',
    'brandon james ltd',
    'bridge recruitment uk limited',
    'bridge rh',
    'brightwater recruitment',
    'bruin',
    'bruin financial',
    'build recruitment',
    'building careers uk ltd',
    'bureau des talents',
    'burton recruitment',
    'business professionals',
    'butler rose',
    'bv recruitment ltd',
    'c&m travel recruitment',
    'cab à talents',
    'campbell grove talent ltd',
    'campion pickworth',
    'capijob',
    'capio recruitment legal',
    'career legal',
    'carlo hefti ag',
    'cast uk limited',
    'cbw staffing solutions ltd',
    'cedar recruitment',
    'cer financial ltd',
    'certain advantage',
    'chad management group',
    'challenger recruitment specialists',
    'chroma recruitment ltd',
    'circle recruitment',
    'city elite transaction services ltd',
    'claims recruitment services',
    'clarity search partners',
    'clayton davies',
    'clayton davies ltd',
    'cld recruitment (leeds) ltd',
    'clear it recruitment limited',
    'cmr jobs limited',
    'collective.work',
    'communicate recruitment solutions ltd',
    'corus consultancy',
    'counted recruitment',
    'cra consulting',
    'cross border talents',
    'crowe watson recruitment',
    'curtis recruitment',
    'daniel owen ltd',
    'darwin hawkins',
    'david aplin recruiting',
    'davies talent solutions',
    'dawn ellmore employment agency',
    'dca recruitment',
    'dgh recruitment',
    'dk recruitment',
    'dk recruitment ltd',
    'dms computer recruitment',
    'douglas scott legal recruitment',
    'dpa professionals',
    'durlston partners',
    'early career',
    'ec1 partners',
    'efinancialcareers',
    'eightmoose.com',
    'eka finance',
    'elevate partners',
    'elevation recruitment group',
    'eleven eleven recruitment ltd',
    'elliot partnership',
    'emagine consulting sarl',
    'emfusion global',
    'engineering search firm',
    'engineering search firm inc',
    'ernest gordon recruitment',
    'ernest gordon recruitment limited',
    'essential recruitment',
    'etech partners',
    'ethos beathchapman',
    'evolve talent partners',
    'example recruitment',
    'executive network legal limited',
    'eximius finance',
    'expectra',
    'expectra search',
    'experienced career',
    'fabric recruitment',
    'fair recruitment',
    'fed finance',
    'fed finance de marché',
    'fed finance réseau',
    'fed group',
    'fed legal',
    'finance professionals',
    'financial divisions',
    'finlink group',
    'fionics',
    'fortus recruitment',
    'forums talents handicap',
    'fraser edwards recruitment',
    'frontier resourcing ltd',
    'fusion medical staffing',
    'g2 legal limited',
    'gail kenny executive recruitment',
    'gcs recruitment',
    'gentis recruitment sas',
    'gerrard white',
    'gerrardwhite',
    'get recruited  ltd',
    'get recruited (uk) ltd',
    'gleeson recruitment group',
    'gloccomslondon',
    'gold group ltd',
    'gordon yates recruiting & training ltd',
    'gpac',
    'gpn recruitment ltd',
    'graduate recruitment bureau',
    'hackajob',
    'hamilton rowe recruitment ltd',
    'hammer search partners',
    'harnham',
    'harnham - data & analytics recruitment',
    'harrison holgate',
    'headhuntersteam',
    'headsource international',
    'hexwired recruitment limited',
    'high finance  limited',
    'high finance  limited t/a hfg',
    'high finance (uk) limited t/a hfg',
    'hill mcglynn recruitment limited',
    'hire up talent',
    'howells recruitment',
    'howett thorpe',
    'hr go recruitment',
    'hunter bond',
    'huntress',
    'hydrogen group',
    'i love my job ltd',
    'ibex recruitment ltd',
    'iconic resourcing ltd',
    'identify solutions',
    'idex consulting ltd',
    'ignite talent solutions',
    'imagine executive solutions',
    'imperium financial recruitment',
    'imt resourcing solutions',
    'imultiply resourcing ltd',
    'independent recruiters',
    'infused solutions ltd',
    'insight global',
    'insite public practice recruitment limited',
    'insure recruitment',
    'inventum group',
    'involve recruitment',
    'io tech solutions limited',
    'ipoe consulting',
    'ips group',
    'ips group uk',
    'irishjobs',
    'itol recruit',
    'jameson legal.',
    'jefferson wells',
    'jm legal ltd',
    'job board direct',
    'job details',
    'job switch ltd',
    'jobgether',
    'jobistart',
    'judge group, inc.',
    'kbc technologies uk ltd',
    'kennedy pearce consulting',
    'kevin theobald employment agency',
    'kforce technology staffing',
    'kingsgate recruitment ltd',
    'ko2 embedded recruitment solutions ltd',
    'larbey evans ltd',
    'law absolute recruitment ltd',
    'law staff legal recruitment ltd',
    'lawes consulting group',
    'lawson chase',
    'le meas executive search',
    'leap recruitment partners',
    'legal & hr talents',
    'link it recruitment',
    'linkit recruitment',
    'lnj recruitment limited',
    'lochead sandford recruitment limited',
    'logan sinclair',
    'lorus partners ltd',
    'lotus partners',
    'love success recruitment',
    'lusona consultancy (financial) limited',
    'lynx rh',
    'madison-davis, llc',
    'marc daniels',
    'market talent',
    'marlin selection',
    'marlin selection ltd',
    'marsden international legal search limited',
    'masalex conseil',
    'mason blake',
    'massenhove recruitment limited',
    'mastarrec',
    'matchtech',
    'matrix recruitment group',
    'mbm travel executives ltd',
    'mcgregor boyall',
    'mcs group',
    'medlock partners limited',
    'mellis blue accountancy recruitment',
    'mentmore recruitment ltd',
    'meraki talent limited',
    'mercor',
    'merje',
    'merje ltd',
    'method resourcing',
    'mindlance',
    'minted search group',
    'mlc partners',
    'mon consultant indépendant',
    'mondrian alpha',
    'mondrian alpha recruitment solutions',
    'montpellier resourcing',
    'more recruitment b.v.',
    'morgan hunt recruitment',
    'morson edge',
    'mpg partners',
    'mpj recruitment ltd',
    'multi trades recruitment',
    'mypetrocareer.com',
    'naden blair',
    'netbox recruitment',
    'newto training',
    'nexoris',
    'niyaa people ltd',
    'njf global holdings ltd',
    'nonstop consulting',
    'norman alex',
    'northbound search',
    'office angels',
    'okwera recruitment',
    'oliver james',
    'oliver james associates',
    'one ten associates',
    'one ten associates ltd',
    'one2one recruitment',
    'opus recruitment solutions ltd',
    'oscar technology',
    'oscar wood',
    'oxford knight',
    'p2p',
    'page executive',
    'page group',
    'paragon alpha - hedge fund talent business',
    'pardus bridge recruitment',
    'parker wright consulting',
    'pathway careers ltd',
    'penguin recruitment ltd',
    'pioneer search',
    'platinum recruitment',
    'pmr',
    'pontoon',
    'premier recruitment group',
    'premier recruitment group limited',
    'pro-finance',
    'pro-recruitment',
    'pro-tax recruitment',
    'procom',
    'profectus recruitment',
    'projob',
    'prospero teaching',
    'qed legal',
    'quant capital',
    'quanta search',
    'quinton davies',
    'radley james',
    'rec sense recruitment',
    'recruit cumbria',
    'recruit wealth',
    'recruiters',
    'recruiting from scratch',
    'reed',
    'reed specialist recruitment',
    'regen solutions',
    'rev & regs limited',
    'rgb recruitment',
    'richard, wayne and roberts',
    'ritz recruitment',
    'rls legal recruitment',
    'robert walters',
    'robert walters uk',
    'robertson & company ltd.',
    'roly recruitment',
    'ryder reid legal limited',
    'ryder reid legal ltd',
    's.i. systems',
    'sacco mann',
    'salt mountain recruitment',
    'salt search',
    'sanderson',
    'sanderson recruitment',
    'saragossa',
    'schollmeyer & steidl gmbh',
    'search',
    'searchability',
    'searchability  ltd',
    'searchability ns&d',
    'sellick partnership',
    'ser (staffing) ltd',
    'service care solutions - legal',
    'sharp consultancy',
    'sharpe wysman',
    'si recruitment',
    'simpson judge ltd',
    'sizanid staffing',
    'sjc partners',
    'skilled careers',
    'skillful',
    'smartsearch recruitment',
    'social capital resources',
    'specialist recruit',
    'spectrum it recruitment',
    'spectrum it recruitment limited',
    'srg',
    'staffing in motion',
    'staffing solutions usa',
    'staffing solutions usa, inc.',
    'staffworks l t d',
    'strictly recruitment',
    'strive recruitment',
    'strive search',
    'talent included',
    'talent smart',
    'talent solutions tapfin',
    'talents finance',
    'targeted talent',
    'taylor root',
    'techchain talent',
    'tempest vane partners',
    'tempositions group of companies',
    'tenth revolution group',
    'the butchers recruiter',
    'the emerald recruiting group',
    'the human capital company',
    'the language business - language recruitment specialists',
    'the legists',
    'the portfolio group',
    'the recruitment experts',
    'theo james recruitment',
    'think recruitment',
    'three bridges recruitment ltd',
    'tqr consultancy ltd',
    'trading careers',
    'trevett professional services ltd',
    'trp recruitment',
    'tsr legal - wales',
    'vaco llc',
    'vaisto recruitment ltd',
    'vallum associates',
    'vanrath',
    'venture search',
    'verelogic recruitment',
    'vermelo',
    'vermelo rpo',
    'vertus partners',
    'victus search',
    'viqu energy limited',
    'viqu it recruitment',
    'virtualvocations',
    'warner scott recruitment ltd',
    'wellington professional recruitment',
    'whatjobs direct',
    'widenet consulting',
    'wild recruitment',
    'wilkinson & associates ltd',
    'winston fox',
    'wintermann search & selection limited',
    'workwise gmbh',
    'yolk recruitment',
    'yolk recruitment limited',
    'yolk recruitment ltd',
    'zachary daniels',
    # Additional agencies spotted in output
    'michael page',
    'michael page international',
    'page personnel',
    'be-it resourcing',
    'innovex resource group limited',
    'innovex resource group',
    'candidate source',
    'candidate source - team',
    'eden rose',
    'charles peters',
    'lantra',
    'evlo',
    # Batch 2 — from aggregator output review
    'abbtech professional resources',
    'actalent',
    'additional resources',
    'adecco',
    'adecco us, inc.',
    'ai jobs at itol recruit',
    'aldwych consulting',
    'aldwych consulting ltd',
    'alexander mae ltd',
    'anderson knight',
    'appleby brown search',
    'artemis search & selection limited',
    'ashville knight',
    'aspire jobs limited',
    'austin rose associates limited',
    'avencia consulting',
    'avencia consulting services',
    'awd online',
    'blackstone talent group',
    'blusource professional services ltd',
    'brandon james',
    'broadgate search',
    'careers integrated resources inc',
    'connect2talentsolutions',
    'consultative search group',
    'cv resources',
    'cyber talent limited',
    'dot recruit',
    'eames consulting',
    'edmund and evans limited',
    'fintec recruit ltd',
    'first choice selection services ltd',
    'french selection',
    'french selection uk',
    'glen callum associates ltd',
    'harkaye core talent limited',
    'hays',
    'hays accountancy and finance',
    'hays business support',
    'hays senior finance',
    'hays technology',
    'heathrow personnel',
    'honeycomb jobs limited',
    'howells solutions limited',
    'hunter savage',
    'huxley',
    'huxley associates',
    'infrasearch.',
    'james joseph associates',
    'james joseph associates limited',
    'jobshop uk limited',
    'katie bard',
    'larbey evans',
    'law staff limited',
    'loom talent limited',
    'manpowergroup',
    'marston search',
    'mcginnis loy associates ltd',
    'mcgregor boyall associates limited',
    'meritus talent',
    'michael page banking',
    'michael page business support',
    'michael page finance',
    'michael page legal',
    'michael page property & construction',
    'michael page technology',
    'mmp consultancy',
    'morgan mckinley',
    'morgan mckinley group ltd',
    'net recruit',
    'oscar associates limited',
    'owen reed',
    'pioneer selection ltd',
    'plummer search',
    'prime personnel',
    'prince personnel limited',
    'pro talent',
    'proactive personnel - telford',
    'pure human resources ltd',
    'puro search',
    'purosearch',
    'randstad construction & property',
    'randstad construction and property',
    'recruit uk',
    'recruitme',
    'red recruit',
    'red recruit ltd',
    'reed technology',
    'remarkable jobs',
    'rg setsquare',
    'rmerecruit',
    'robert half',
    'robert half limited',
    'rutherford briant',
    'sanderson government and defence',
    'sc staff and consult',
    'search jobs in cumbria',
    'selby jennings',
    'selby jennings london',
    'square one resources',
    'stabile search',
    'staffline',
    'sthree uk',
    'summer browning associates',
    'synergi search & select limited',
    'talent finder',
    'talent guardian',
    'talent link',
    'talent software services',
    'talenttrade',
    'teksystems',
    'teksystems c/o allegis group',
    'thomas search ltd',
    'tn recruits',
    'top recruit',
    'trustedlocal jobs',
    'txm recruit',
    'winston resources',
    'yourrecruit',
    'yourrecruit limited',
    'capitex',
    # Added from Coresignal 30-day sweep leak audit
    'aej consulting ltd',
    'airswift',
    'alexander chapman',
    'apex systems',
    'attribution search',
    'barclay simpson',
    'bwd search & selection',
    'client server',
    'crossing hurdles',
    'goodman masson',
    'haystack',
    'leverton search',
    'lorien',
    'ocr alpha',
    'orbis group',
    'pharos resource partners',
    'pontoon solutions',
    'stanford black limited',
    'statera talent',
    'tardis group',
    'templeton & partners',
    'track legal',
    'trevose partners',
    'venture up',
    'vertex search',
    'xcede',
    'youngcapital',
}

# Keyword fallback — catches agencies not yet in the list above
RECRUITER_KEYWORDS: tuple[str, ...] = (
    "recruitment", "recruiting", "recruiter", "staffing",
    "headhunt", "head hunt", "executive search",
    "talent acqui", "talent solution", "talent partner",
    "personnel agency", "employment agency",
    "search firm", "search partner",
    "placement", "temp agency",
)


# Runtime exclusions are appended to this YAML whenever the operator marks
# a company as an agency via the UI (or CLI). Path is configurable via the
# AGENCY_EXCLUSIONS_PATH env var so in containerised prod deployments the
# file can live on a persistent volume / Azure Files mount rather than
# inside the ephemeral image. Default matches local-dev conventions.
_RUNTIME_EXCLUSIONS_PATH = Path(os.getenv("AGENCY_EXCLUSIONS_PATH") or "configs/agency_exclusions.yaml")
_RUNTIME_EXCLUSIONS: set[str] = set()


def _load_runtime_exclusions() -> set[str]:
    if not _RUNTIME_EXCLUSIONS_PATH.exists():
        return set()
    try:
        with _RUNTIME_EXCLUSIONS_PATH.open("r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh) or {}
    except Exception as exc:  # noqa: BLE001
        logger.warning("Failed to load %s: %s", _RUNTIME_EXCLUSIONS_PATH, exc)
        return set()
    names = data.get("agencies") or []
    return {str(n).strip().lower() for n in names if str(n).strip()}


def refresh_runtime_exclusions() -> int:
    """Re-read configs/agency_exclusions.yaml. Returns the loaded count."""
    global _RUNTIME_EXCLUSIONS
    _RUNTIME_EXCLUSIONS = _load_runtime_exclusions()
    return len(_RUNTIME_EXCLUSIONS)


def add_agency_exclusion(company: str) -> bool:
    """Append a company name to the runtime YAML exclusion list.

    Returns True if newly added, False if already present (in either the
    hardcoded set or the runtime set).

    The YAML at _RUNTIME_EXCLUSIONS_PATH is the source of truth for runtime
    additions. In containerised deployments this path should be pointed at a
    persistent volume (via the AGENCY_EXCLUSIONS_PATH env var) so runtime
    additions survive restarts. Inside the default local-dev setup the file
    lives in the repo at configs/agency_exclusions.yaml.

    Historical note: this function previously shelled out to `git add` +
    `git commit` after a successful YAML append, so the repo working tree
    tracked runtime additions. That subprocess was removed 2026-04-20 — it
    crashes inside containers (no git binary, no repo) and makes the
    endpoint unsafe to deploy. Re-introducing similar behaviour needs to be
    done via an out-of-band change-request flow, not an in-request
    subprocess.
    """
    if not company or not company.strip():
        return False
    norm = company.strip().lower()
    if norm in EXCLUDED_RECRUITERS or norm in _RUNTIME_EXCLUSIONS:
        return False

    _RUNTIME_EXCLUSIONS_PATH.parent.mkdir(parents=True, exist_ok=True)
    if _RUNTIME_EXCLUSIONS_PATH.exists():
        with _RUNTIME_EXCLUSIONS_PATH.open("r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh) or {}
    else:
        data = {}
    agencies = list(data.get("agencies") or [])
    agencies.append(norm)
    data["agencies"] = agencies
    with _RUNTIME_EXCLUSIONS_PATH.open("w", encoding="utf-8") as fh:
        yaml.safe_dump(data, fh, sort_keys=False, allow_unicode=True)
    refresh_runtime_exclusions()
    logger.info(
        "agency-exclusion added at runtime: %s (written to %s). "
        "Ensure this path is persisted across container restarts in prod.",
        norm, _RUNTIME_EXCLUSIONS_PATH,
    )
    return True


# Populate runtime cache at import time. Tolerates missing file.
refresh_runtime_exclusions()


def _alphanum_tokens(s: str) -> set[str]:
    """Tokenise on word boundaries, dropping punctuation. 'McCabe & Barton'
    and 'McCabe Barton' both yield {mccabe, barton}."""
    return set(re.findall(r"[a-z0-9]+", s.lower()))


def is_recruiter(company: str | None) -> bool:
    """Return True if the company looks like a recruitment agency.

    Match order:
      1. Exact lowercase match against the hardcoded EXCLUDED_RECRUITERS or
         the runtime YAML exclusions. (Fastest, strictest.)
      2. Token-subset match against the runtime YAML exclusions. So a YAML
         entry of 'korn ferry' catches 'Korn Ferry International',
         'Korn Ferry UK Ltd', etc. Entries are tokenised on alphanumeric
         word boundaries so 'mccabe & barton' (with the &) still matches
         'McCabe Barton Recruiting' (without the &). Prevents the common
         "I marked agency, why are they back?" foot-gun where the next
         scrape returns a slightly-decorated form of the company name.
      3. Substring match against RECRUITER_KEYWORDS (the heuristic catch-all
         like 'recruit', 'staffing', 'talent solutions', etc.).
    """
    if not company:
        return False
    norm = company.strip().lower()
    if norm in EXCLUDED_RECRUITERS or norm in _RUNTIME_EXCLUSIONS:
        return True

    candidate_tokens = _alphanum_tokens(norm)
    if candidate_tokens:
        for entry in _RUNTIME_EXCLUSIONS:
            entry_tokens = _alphanum_tokens(entry)
            if entry_tokens and entry_tokens.issubset(candidate_tokens):
                return True

    return any(kw in norm for kw in RECRUITER_KEYWORDS)
