
"""
Central configuration: all 801 unique job board URLs, platform routing,
and pre-parsed Workday board structs.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from urllib.parse import urlparse


@dataclass
class WorkdayBoard:
    board_url: str
    tenant: str
    shard: str
    site_path: str
    company: str = ""

    @property
    def api_url(self) -> str:
        return (
            f"https://{self.tenant}.{self.shard}.myworkdayjobs.com"
            f"/wday/cxs/{self.tenant}/{self.site_path}/jobs"
        )

    @property
    def domain(self) -> str:
        return f"{self.tenant}.{self.shard}.myworkdayjobs.com"


def _parse_workday_url(url: str, company: str = "") -> WorkdayBoard:
    parsed = urlparse(url)
    host = parsed.netloc.lower()
    parts = [p for p in parsed.path.split("/") if p]
    if "myworkdayjobs.com" in host:
        subdomain_parts = host.split(".")
        tenant = subdomain_parts[0]
        shard = subdomain_parts[1]
        site_path = parts[-1] if parts else tenant
    else:
        shard = host.split(".")[0]
        tenant = parts[2] if len(parts) > 2 else parts[-2]
        site_path = parts[3] if len(parts) > 3 else parts[-1]
    return WorkdayBoard(board_url=url, tenant=tenant, shard=shard, site_path=site_path, company=company)


WORKDAY_BOARDS: list[WorkdayBoard] = [
    _parse_workday_url("https://abrdn.wd3.myworkdayjobs.com/en-US/abrdn", "abrdn"),
    _parse_workday_url("https://absa.wd3.myworkdayjobs.com/en-US/ABSAcareersite", "ABSA"),
    _parse_workday_url("https://aegislondon.wd3.myworkdayjobs.com/en-US/Careers", "AEGIS London"),
    _parse_workday_url("https://transamerica.wd5.myworkdayjobs.com/en-US/AUK_JobSite", "Aegon"),
    _parse_workday_url("https://transamerica.wd5.myworkdayjobs.com/en-US/AEGONAM", "Aegon Asset Management"),
    _parse_workday_url("https://aig.wd1.myworkdayjobs.com/en-US/aig", "AIG"),
    _parse_workday_url("https://abglobal.wd1.myworkdayjobs.com/alliancebernsteincareers", "AllianceBernstein"),
    _parse_workday_url("https://awg.wd3.myworkdayjobs.com/en-US/aw", "Anglian Water"),
    _parse_workday_url("https://antaresunderwriting.wd3.myworkdayjobs.com/Antares", "Antares Insurance Company Limited"),
    _parse_workday_url("https://theapexgroup.wd3.myworkdayjobs.com/en-US/apexgroupcareers", "APEX"),
    _parse_workday_url("https://athene.wd5.myworkdayjobs.com/Apollo_Careers", "Apollo"),
    _parse_workday_url("https://athene.wd5.myworkdayjobs.com/en-US/Apollo_Careers", "Apollo"),
    _parse_workday_url("https://archgroup.wd1.myworkdayjobs.com/en-US/Careers", "Arch"),
    _parse_workday_url("https://archgroup.wd1.myworkdayjobs.com/Careers", "Arch Insurance (UK) Limited"),
    _parse_workday_url("https://aresmgmt.wd1.myworkdayjobs.com/en-US/External", "Ares"),
    _parse_workday_url("https://aresmgmt.wd1.myworkdayjobs.com/External", "Ares Management"),
    _parse_workday_url("https://arrowstreetcapital.wd5.myworkdayjobs.com/en-US/Arrowstreet", "Arrowstreet Capital"),
    _parse_workday_url("https://collinsongroup.wd103.myworkdayjobs.com/The_Collinson_Group_External", "Astrenska Insurance Limited"),
    _parse_workday_url("https://aviva.wd1.myworkdayjobs.com/en-US/External", "Aviva"),
    _parse_workday_url("https://axiscapital.wd1.myworkdayjobs.com/axiscareers", "AXIS"),
    _parse_workday_url("https://axiscapital.wd1.myworkdayjobs.com/en-US/axiscareers", "AXIS"),
    _parse_workday_url("https://ayvens.wd3.myworkdayjobs.com/en-US/AyvensCareers", "Ayvens"),
    _parse_workday_url("https://aztecgroup.wd103.myworkdayjobs.com/en-US/External", "Aztec Group"),
    _parse_workday_url("https://bailliegifford.wd3.myworkdayjobs.com/en-US/BaillieGiffordCareers", "Baillie Gifford"),
    _parse_workday_url("https://barings.wd1.myworkdayjobs.com/en-US/Barings", "Barings"),
    _parse_workday_url("https://bbva.wd3.myworkdayjobs.com/en-US/BBVA", "BBVA"),
    _parse_workday_url("https://blackrock.wd1.myworkdayjobs.com/en-US/BlackRock_Professional", "BlackRock"),
    _parse_workday_url("https://blackstone.wd1.myworkdayjobs.com/en-US/Blackstone_Careers", "Blackstone"),
    _parse_workday_url("https://blackstone.wd1.myworkdayjobs.com/en-US/Blackstone_Campus_Careers", "Blackstone"),
    _parse_workday_url("https://blueowl.wd1.myworkdayjobs.com/blueowl", "Blue Owl"),
    _parse_workday_url("https://bpinternational.wd3.myworkdayjobs.com/en-US/bpCareers", "BP"),
    _parse_workday_url("https://bp.wd3.myworkdayjobs.com/bp_ExternalCareerSite", "BP"),
    _parse_workday_url("https://wd3.myworkdaysite.com/recruiting/brevanhoward/BH_ExternalCareers", "Brevan Howard"),
    _parse_workday_url("https://wd3.myworkdaysite.com/en-US/recruiting/brevanhoward/BH_ExternalCareers", "Brevan Howard"),
    _parse_workday_url("https://broadridge.wd5.myworkdayjobs.com/External_Career_Site", "Broadridge"),
    _parse_workday_url("https://brookfield.wd5.myworkdayjobs.com/en-US/brookfield", "Brookfield"),
    _parse_workday_url("https://bbinsurance.wd1.myworkdayjobs.com/en-US/Careers_Europe", "Brown & Brown"),
    _parse_workday_url("https://capgroup.wd1.myworkdayjobs.com/en-US/capitalgroupcareers", "Capital Group"),
    _parse_workday_url("https://osv-cci.wd1.myworkdayjobs.com/CCICareers", "Castleton Commodities International"),
    _parse_workday_url("https://centrica.wd3.myworkdayjobs.com/en-US/Centrica", "Centrica"),
    _parse_workday_url("https://challenger.wd3.myworkdayjobs.com/en-US/Challenger_Careers", "Challenger"),
    _parse_workday_url("https://chaucergroup.wd3.myworkdayjobs.com/en-US/chaucer_group_careers", "Chaucer"),
    _parse_workday_url("https://chevron.wd5.myworkdayjobs.com/en-US/jobs", "Chevron"),
    _parse_workday_url("https://cibc.wd3.myworkdayjobs.com/en-US/search", "CIBC"),
    _parse_workday_url("https://cigna.wd5.myworkdayjobs.com/en-US/cignacareers", "Cigna"),
    _parse_workday_url("https://citi.wd5.myworkdayjobs.com/en-US/2", "Citi"),
    _parse_workday_url("https://cmegroup.wd1.myworkdayjobs.com/en-US/cme_careers", "CME Group"),
    _parse_workday_url("https://cna.wd1.myworkdayjobs.com/CNAHardy", "CNA"),
    _parse_workday_url("https://cna.wd1.myworkdayjobs.com/en-US/CNAHardy", "CNA Hardy"),
    _parse_workday_url("https://cmegroup.wd1.myworkdayjobs.com/en-US/cme_careers", "COMEX"),
    _parse_workday_url("https://cba.wd3.myworkdayjobs.com/en-US/CommBank_Careers", "Commonwealth Bank"),
    _parse_workday_url("https://corpay.wd103.myworkdayjobs.com/en-US/Ext_001", "Corpay"),
    _parse_workday_url("https://customersbank.wd1.myworkdayjobs.com/customersbankcareers", "Customers Bank"),
    _parse_workday_url("https://db.wd3.myworkdayjobs.com/de-DE/DBWebsite", "Deutsche Bank"),
    _parse_workday_url("https://dlg.wd3.myworkdayjobs.com/en-US/DLGCAREERS", "Direct Line"),
    _parse_workday_url("https://domesticandgeneral.wd3.myworkdayjobs.com/en-US/DeGCareers", "Domestic & General"),
    _parse_workday_url("https://eonnext.wd3.myworkdayjobs.com/en-US/EON_Next_Careers", "E.ON Next"),
    _parse_workday_url("https://edftrading.wd1.myworkdayjobs.com/en-US/EDFTrading", "EDF"),
    _parse_workday_url("https://edftrading.wd1.myworkdayjobs.com/en-US/EDFTrading?act=redirectCws&cws=40&org=edftrading2", "EDF Trading"),
    _parse_workday_url("https://equinor.wd3.myworkdayjobs.com/EQNR", "Equinor"),
    _parse_workday_url("https://hrhub.wd3.myworkdayjobs.com/en-US/Euronext_Career_Page", "Euronext"),
    _parse_workday_url("https://wd5.myworkdaysite.com/recruiting/everestre/careers", "Everest"),
    _parse_workday_url("https://wd5.myworkdaysite.com/en-US/recruiting/everestre/careers", "Everest"),
    _parse_workday_url("https://factset.wd108.myworkdayjobs.com/FactSetCareers", "FactSet"),
    _parse_workday_url("https://fil.wd3.myworkdayjobs.com/en-US/001", "Fidelity International"),
    _parse_workday_url("https://fei.wd5.myworkdayjobs.com/en-US/External", "First Eagle Investments"),
    _parse_workday_url("https://fortress.wd503.myworkdayjobs.com/Careers", "Fortress Investment Group"),
    _parse_workday_url("https://gam.wd3.myworkdayjobs.com/GAM", "GAM Systematic"),
    _parse_workday_url("https://wintrust.wd1.myworkdayjobs.com/Search", "Glenview Capital Management"),
    _parse_workday_url("https://wd501.myworkdaysite.com/recruiting/golubcapital/Golub_Capital_Careers", "Golub Capital"),
    _parse_workday_url("https://guggenheim.wd1.myworkdayjobs.com/Guggenheim_Partners", "Guggenheim"),
    _parse_workday_url("https://guggenheim.wd1.myworkdayjobs.com/Guggenheim_Careers", "Guggenheim"),
    _parse_workday_url("https://guggenheiminvestment.wd5.myworkdayjobs.com/External", "Guggenheim"),
    _parse_workday_url("https://gunvor.wd3.myworkdayjobs.com/Gunvor_Careers", "Gunvor"),
    _parse_workday_url("https://hamiltonlane.wd108.myworkdayjobs.com/en-us/search", "Hamilton Lane"),
    _parse_workday_url("https://harbourvest.wd5.myworkdayjobs.com/en-US/HVP", "HarbourVest"),
    _parse_workday_url("https://hargreaveslansdown.wd3.myworkdayjobs.com/en-US/HargreavesLansdown", "Hargreaves Lansdown"),
    _parse_workday_url("https://hastingsdirect.wd3.myworkdayjobs.com/en-US/external_careers", "Hastings Direct"),
    _parse_workday_url("https://hiscox.wd3.myworkdayjobs.com/en-US/Hiscox_External_Site", "Hiscox"),
    _parse_workday_url("https://hiscox.wd3.myworkdayjobs.com/Hiscox_External_Site", "Hiscox Insurance Company Limited"),
    _parse_workday_url("https://hkex.wd3.myworkdayjobs.com/en-US/HKEXCareerPage", "HKEX"),
    _parse_workday_url("https://hl.wd1.myworkdayjobs.com/Lateral", "Houlihan Lokey"),
    _parse_workday_url("https://hl.wd1.myworkdayjobs.com/en-US/Lateral", "Houlihan Lokey"),
    _parse_workday_url("https://hyperiongrp.wd3.myworkdayjobs.com/en-US/hyperion_external", "Howden Group Holdings"),
    _parse_workday_url("https://iberdrola.wd3.myworkdayjobs.com/en-US/Iberdrola", "Iberdrola"),
    _parse_workday_url("https://icg.wd3.myworkdayjobs.com/en-US/external_careers", "ICG"),
    _parse_workday_url("https://intrum.wd3.myworkdayjobs.com/en-US/External", "Intrum"),
    _parse_workday_url("https://invesco.wd1.myworkdayjobs.com/en-GB/IVZ", "Invesco"),
    _parse_workday_url("https://perpetual.wd3.myworkdayjobs.com/en-US/JOHCM_External", "J O Hambro Capital Management"),
    _parse_workday_url("https://jainglobal.wd5.myworkdayjobs.com/en-US/ExternalSite", "Jain Global"),
    _parse_workday_url("https://pru.wd5.myworkdayjobs.com/en-US/Careers/?q=&locationCountry=bc33aa3152ec42d4995f4791a106ed09", "Jennison Associates"),
    _parse_workday_url("https://jupiteram.wd3.myworkdayjobs.com/en-US/jupiter_careers", "Jupiter"),
    _parse_workday_url("https://just.wd3.myworkdayjobs.com/en-US/JUST_External", "Just"),
    _parse_workday_url("https://krgroup.wd3.myworkdayjobs.com/en-US/KR_Group", "KeyGroup"),
    _parse_workday_url("https://lloyds.wd3.myworkdayjobs.com/en-US/Lloyds-of-London", "Lloyd's"),
    _parse_workday_url("https://lseg.wd3.myworkdayjobs.com/Careers", "LSEG"),
    _parse_workday_url("https://lseg.wd3.myworkdayjobs.com/en-US/Careers", "LSEG"),
    _parse_workday_url("https://mgpru.wd3.myworkdayjobs.com/en-US/mandgprudential", "M&G Prudential"),
    _parse_workday_url("https://mtb.wd5.myworkdayjobs.com/en-US/MTB", "M&T Bank"),
    _parse_workday_url("https://marex.wd3.myworkdayjobs.com/Marex_Careers", "Marex"),
    _parse_workday_url("https://markelcorp.wd5.myworkdayjobs.com/en-US/GlobalCareers", "Markel"),
    _parse_workday_url("https://mastercard.wd1.myworkdayjobs.com/en-US/CorporateCareers", "Mastercard"),
    _parse_workday_url("https://mfs.wd1.myworkdayjobs.com/en-US/MFS-Careers", "MFS"),
    _parse_workday_url("https://moelis.wd1.myworkdayjobs.com/en-US/Experienced-Hires", "Moelis & Company"),
    _parse_workday_url("https://morningstar.wd5.myworkdayjobs.com/en-US/Americas", "Morningstar"),
    _parse_workday_url("https://msamlin.wd3.myworkdayjobs.com/en-US/MSAmlinCareers", "MS Amlin"),
    _parse_workday_url("https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers", "MUFG"),
    _parse_workday_url("https://muzinich.wd5.myworkdayjobs.com/en-US/muzinichcareers", "Muzinich & Co."),
    _parse_workday_url("https://nasdaq.wd1.myworkdayjobs.com/en-US/Global_External_Site", "Nasdaq"),
    _parse_workday_url("https://rbs.wd3.myworkdayjobs.com/en-US/RBS", "NatWest Group"),
    _parse_workday_url("https://nb.wd1.myworkdayjobs.com/en-US/NBCareers", "Neuberger Berman"),
    _parse_workday_url("https://newcastle.wd3.myworkdayjobs.com/en-US/NBSCareers", "Newcastle Building Society"),
    _parse_workday_url("https://newday.wd3.myworkdayjobs.com/en-US/NewDay", "NewDay"),
    _parse_workday_url("https://nibcatwork.wd3.myworkdayjobs.com/en-US/External", "NIBC Bank"),
    _parse_workday_url("https://ntrs.wd1.myworkdayjobs.com/en-US/northerntrust", "Northern Trust"),
    _parse_workday_url("https://oaktree.wd1.myworkdayjobs.com/en-US/Oaktree", "Oaktree"),
    _parse_workday_url("https://oldmutual.wd3.myworkdayjobs.com/en-US/Old_Mutual_Careers", "Old Mutual"),
    _parse_workday_url("https://pacificlife.wd1.myworkdayjobs.com/en-US/PacificLifeReCareers", "Pacific Life Re"),
    _parse_workday_url("https://perpetual.wd3.myworkdayjobs.com/en-US/external", "Perpetual"),
    _parse_workday_url("https://pibgroup.wd3.myworkdayjobs.com/en-US/PIB", "PIB Group"),
    _parse_workday_url("https://pimco.wd1.myworkdayjobs.com/en-US/pimco-careers", "PIMCO"),
    _parse_workday_url("https://pjtpartners.wd1.myworkdayjobs.com/en-US/Careers", "PJT Partners"),
    _parse_workday_url("https://progleasing.wd5.myworkdayjobs.com/en-US/ProgLeasingCareers", "Progressive Leasing"),
    _parse_workday_url("https://wd5.myworkdaysite.com/en-US/recruiting/pru/Careers", "Prudential Financial"),
    _parse_workday_url("https://qbe.wd3.myworkdayjobs.com/en-US/QBE-Careers", "QBE Insurance"),
    _parse_workday_url("https://quilter.wd3.myworkdayjobs.com/en-US/External-Career-Site", "Quilter"),
    _parse_workday_url("https://rabobank.wd3.myworkdayjobs.com/en-US/jobs", "Rabobank"),
    _parse_workday_url("https://railpen.wd3.myworkdayjobs.com/en-US/Railpen", "Railpen"),
    _parse_workday_url("https://rothschildandco.wd3.myworkdayjobs.com/en-US/RothschildAndCo_Lateral", "Rothschild & Co"),
    _parse_workday_url("https://ryansg.wd5.myworkdayjobs.com/en-US/Ryan_Specialty_Career_Site", "Ryan Specialty"),
    _parse_workday_url("https://santander.wd3.myworkdayjobs.com/en-US/SantanderCareers", "Santander"),
    _parse_workday_url("https://spw.wd3.myworkdayjobs.com/en-US/spw_careers", "Schroders Personal Wealth"),
    _parse_workday_url("https://scottishwater.wd3.myworkdayjobs.com/en-US/External_Careers", "Scottish Water"),
    _parse_workday_url("https://sedgwick.wd1.myworkdayjobs.com/en-US/Sedgwick", "Sedgwick"),
    _parse_workday_url("https://seic.wd1.myworkdayjobs.com/en-US/SEI_Global_Services", "SEI"),
    _parse_workday_url("https://shell.wd3.myworkdayjobs.com/en-US/ShellCareers", "Shell Global"),
    _parse_workday_url("https://skipton.wd3.myworkdayjobs.com/en-US/Careers-Skipton", "Skipton Building Society"),
    _parse_workday_url("https://endurance.wd103.myworkdayjobs.com/en-US/SompoInternational", "Sompo International"),
    _parse_workday_url("https://starrcompanies.wd1.myworkdayjobs.com/en-US/careers", "Starr Companies"),
    _parse_workday_url("https://statestreet.wd1.myworkdayjobs.com/en-US/Global", "State Street"),
    _parse_workday_url("https://stonex.wd1.myworkdayjobs.com/en-US/STONEX", "StoneX"),
    _parse_workday_url("https://troweprice.wd5.myworkdayjobs.com/en-US/TRowePriceInternational", "T. Rowe Price"),
    _parse_workday_url("https://td.wd3.myworkdayjobs.com/en-US/TD_Bank_Careers", "TD"),
    _parse_workday_url("https://tmhcc.wd108.myworkdayjobs.com/en-US/External", "Tokio Marine HCC"),
    _parse_workday_url("https://tokiomarinekiln.wd3.myworkdayjobs.com/en-US/TMK_Careers", "Tokio Marine Kiln"),
    _parse_workday_url("https://tp.wd107.myworkdayjobs.com/en-US/TP-ICAP", "TP ICAP"),
    _parse_workday_url("https://travelex.wd107.myworkdayjobs.com/en-US/TravelexCareers", "Travelex"),
    _parse_workday_url("https://ukib.wd3.myworkdayjobs.com/en-US/UKIB", "UK Infrastructure Bank"),
    _parse_workday_url("https://unum.wd1.myworkdayjobs.com/en-US/External", "Unum"),
    _parse_workday_url("https://usbank.wd1.myworkdayjobs.com/en-US/US_Bank_Careers", "US Bank"),
    _parse_workday_url("https://vanguard.wd5.myworkdayjobs.com/en-US/vanguard_external", "Vanguard"),
    _parse_workday_url("https://cgg.wd103.myworkdayjobs.com/en-US/viridiencareers", "Viridien"),
    _parse_workday_url("https://godirect.wd5.myworkdayjobs.com/en-US/voya_jobs", "Voya Financial"),
    _parse_workday_url("https://wellington.wd5.myworkdayjobs.com/en-US/External", "Wellington Management"),
    _parse_workday_url("https://wd1.myworkdaysite.com/en-US/recruiting/wf/WellsFargoJobs", "Wells Fargo"),
    _parse_workday_url("https://wfscorp.wd5.myworkdayjobs.com/en-US/wfscareers", "World Fuel Services"),
    _parse_workday_url("https://ardian.wd103.myworkdayjobs.com/ArdianCareers", "Ardian"),
    _parse_workday_url("https://chathamfinancial.wd501.myworkdayjobs.com/ChathamFinancial", "Chatham Financial"),
    _parse_workday_url("https://clearwateranalytics.wd1.myworkdayjobs.com/Clearwater_Analytics_Careers", "Enfusion"),
]

ORACLE_BOARDS: list[dict] = [
    {"url": "https://fa-emkq-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX", "company": "Ascot"},
    {"url": "https://ejjl.fa.ap1.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1", "company": "AustralianSuper"},
    {"url": "https://eoff.fa.em1.ukg.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "Bank of England"},
    {"url": "https://hdid.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX", "company": "Jefferies"},
    {"url": "https://hdow.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003", "company": "BGC"},
    {"url": "https://hdow.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003", "company": "BGC Group"},
    {"url": "https://eofe.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/BNY-Careers", "company": "BNY"},
    {"url": "https://hdow.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003", "company": "Canopius"},
    {"url": "https://hdow.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003", "company": "Cantor Fitzgerald"},
    {"url": "https://hdfg.fa.em3.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX", "company": "Charles Stanley"},
    {"url": "https://fa-ewgu-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001", "company": "Chubb"},
    {"url": "https://fa-euxc-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1", "company": "CITCO"},
    {"url": "https://fa-evdq-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001", "company": "Computershare"},
    {"url": "https://fa-evdq-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/computersharecareers", "company": "Computershare"},
    {"url": "https://ejqi.fa.ocs.oraclecloud.eu/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "Danske Bank"},
    {"url": "https://iabcbn.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/DLL/jobs?mode=location", "company": "DLL"},
    {"url": "https://ebxr.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/jobs?lastSelectedFacet=CATEGORIES&selectedCategoriesFacet=300000002081619", "company": "DTCC"},
    {"url": "https://ebxr.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1", "company": "DTCC"},
    {"url": "https://fa-eqai-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "EFG"},
    {"url": "https://fa-evkm-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1004", "company": "Eni"},
    {"url": "https://don.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003", "company": "Euroclear"},
    {"url": "https://hdow.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003/jobs?mode=location", "company": "FMX"},
    {"url": "https://hdow.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003/jobs?mode=location", "company": "GFI Group"},
    {"url": "https://hdpc.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/LateralHiring", "company": "HDFC"},
    {"url": "https://enlc.fa.ap1.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "IFM Investors"},
    {"url": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "JPMorgan Chase"},
    {"url": "https://dnn.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/Nationwide", "company": "Nationwide"},
    {"url": "https://fa-enor-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX", "company": "Phoenix"},
    {"url": "https://ekbq.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2", "company": "Schroders"},
    {"url": "https://fa-errt-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001", "company": "SCOR"},
    {"url": "https://fa-exdv-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/Careers", "company": "Westfield Specialty"},
    {"url": "https://ebuu.fa.ap1.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX", "company": "Westpac Banking"},
    {"url": "https://eedu.fa.em3.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003", "company": "Willis Towers Watson"},
]

GREENHOUSE_BOARDS: list[dict] = [
    {"url": "https://job-boards.eu.greenhouse.io/mangroup", "company": "AHL Partners", "slug": "mangroup"},
    {"url": "https://boards.greenhouse.io/alpaca", "company": "Alpaca", "slug": "alpaca"},
    {"url": "https://job-boards.greenhouse.io/tpgcareers", "company": "Angelo Gordon", "slug": "tpgcareers"},
    {"url": "https://job-boards.eu.greenhouse.io/apollosyndicate1969/jobs", "company": "Apollo", "slug": "apollosyndicate1969"},
    {"url": "https://boards.greenhouse.io/aztecgroup/jobs", "company": "Aztec Group", "slug": "aztecgroup"},
    {"url": "https://job-boards.greenhouse.io/bluecrestcapitalmanagement", "company": "BlueCrest Capital Management", "slug": "bluecrestcapitalmanagement"},
    {"url": "https://boards.greenhouse.io/brex/jobs", "company": "Brex", "slug": "brex"},
    {"url": "https://job-boards.greenhouse.io/carta", "company": "Carta", "slug": "carta"},
    {"url": "https://boards.greenhouse.io/chime/jobs", "company": "Chime", "slug": "chime"},
    {"url": "https://boards.greenhouse.io/coinbase/jobs", "company": "Coinbase", "slug": "coinbase"},
    {"url": "https://job-boards.greenhouse.io/drweng/jobs", "company": "DRW Holdings", "slug": "drweng"},
    {"url": "https://job-boards.greenhouse.io/engelhart", "company": "Engelhart", "slug": "engelhart"},
    {"url": "https://job-boards.greenhouse.io/exoduspoint", "company": "ExodusPoint", "slug": "exoduspoint"},
    {"url": "https://job-boards.greenhouse.io/faralloncapitalmanagementllc", "company": "Farallon", "slug": "faralloncapitalmanagementllc"},
    {"url": "https://job-boards.greenhouse.io/figure", "company": "Figure", "slug": "figure"},
    {"url": "https://boards.greenhouse.io/flowtraders", "company": "Flow Traders", "slug": "flowtraders"},
    {"url": "https://boards.greenhouse.io/hrttalentcommunity", "company": "Hudson River Trading", "slug": "hrttalentcommunity"},
    {"url": "https://job-boards.greenhouse.io/ibkr", "company": "Interactive Brokers", "slug": "ibkr"},
    {"url": "https://job-boards.eu.greenhouse.io/lhvuk/jobs", "company": "LHV", "slug": "lhvuk"},
    {"url": "https://job-boards.greenhouse.io/lonepinecapital", "company": "Lone Pine Capital", "slug": "lonepinecapital"},
    {"url": "https://job-boards.eu.greenhouse.io/mangroup/jobs", "company": "Man Group", "slug": "mangroup"},
    {"url": "https://boards.greenhouse.io/marqeta/jobs", "company": "Marqeta", "slug": "marqeta"},
    {"url": "https://job-boards.greenhouse.io/mavensecuritiesholdingltd/jobs", "company": "Maven", "slug": "mavensecuritiesholdingltd"},
    {"url": "https://boards.greenhouse.io/memx", "company": "MEMX", "slug": "memx"},
    {"url": "https://boards.greenhouse.io/monzo/jobs", "company": "Monzo", "slug": "monzo"},
    {"url": "https://job-boards.greenhouse.io/pharomanagement/jobs", "company": "Pharo Management", "slug": "pharomanagement"},
    {"url": "https://job-boards.eu.greenhouse.io/policyexpert/jobs", "company": "Policy Expert", "slug": "policyexpert"},
    {"url": "https://boards.greenhouse.io/public", "company": "Public", "slug": "public"},
    {"url": "https://boards.greenhouse.io/robinhood/jobs", "company": "Robinhood", "slug": "robinhood"},
    {"url": "https://job-boards.greenhouse.io/rothesaylife/jobs", "company": "Rothesay", "slug": "rothesaylife"},
    {"url": "https://job-boards.eu.greenhouse.io/srm/jobs", "company": "SRM", "slug": "srm"},
    {"url": "https://boards.greenhouse.io/stripe/jobs", "company": "Stripe", "slug": "stripe"},
    {"url": "https://boards.greenhouse.io/towerresearchcapital", "company": "Tower Research Capital", "slug": "towerresearchcapital"},
    {"url": "https://job-boards.greenhouse.io/walleyecapital-external-fulltime", "company": "Walleye Capital", "slug": "walleyecapital-external-fulltime"},
    {"url": "https://job-boards.eu.greenhouse.io/winton/jobs", "company": "Winton", "slug": "winton"},
    {"url": "https://job-boards.greenhouse.io/affirm", "company": "Affirm", "slug": "affirm"},
    {"url": "https://job-boards.greenhouse.io/assuredguaranty", "company": "Assured Guaranty", "slug": "assuredguaranty"},
    {"url": "https://job-boards.greenhouse.io/bridgewater89", "company": "Bridgewater Associates", "slug": "bridgewater89"},
    {"url": "https://job-boards.greenhouse.io/cais", "company": "CAIS", "slug": "cais"},
    {"url": "https://job-boards.greenhouse.io/cohensteers", "company": "Cohen & Steers", "slug": "cohensteers"},
    {"url": "https://job-boards.greenhouse.io/drivewealth", "company": "DriveWealth", "slug": "drivewealth"},
    {"url": "https://job-boards.eu.greenhouse.io/eqtpartners", "company": "EQT", "slug": "eqtpartners"},
    {"url": "https://job-boards.greenhouse.io/falconx", "company": "FalconX", "slug": "falconx"},
    {"url": "https://job-boards.greenhouse.io/gsacapital", "company": "GSA Capital", "slug": "gsacapital"},
    {"url": "https://job-boards.greenhouse.io/generalatlantic", "company": "General Atlantic", "slug": "generalatlantic"},
    {"url": "https://job-boards.greenhouse.io/grahamcapitalmanagement", "company": "Graham Capital", "slug": "grahamcapitalmanagement"},
    {"url": "https://job-boards.greenhouse.io/hbkcapitalmanagement", "company": "HBK Capital Management", "slug": "hbkcapitalmanagement"},
    {"url": "https://job-boards.greenhouse.io/iex", "company": "IEX Group", "slug": "iex"},
    {"url": "https://job-boards.greenhouse.io/stage", "company": "KKR", "slug": "stage"},
]

ASHBY_BOARDS: list[dict] = [
    {"url": "https://jobs.ashbyhq.com/allica-bank", "company": "Allica Bank", "slug": "allica-bank"},
    {"url": "https://jobs.ashbyhq.com/better-mortgage", "company": "Better", "slug": "better-mortgage"},
    {"url": "https://jobs.ashbyhq.com/ledger", "company": "LedgerX", "slug": "ledger"},
    {"url": "https://jobs.ashbyhq.com/chainalysis-careers", "company": "Chainalysis", "slug": "chainalysis-careers"},
    {"url": "https://jobs.ashbyhq.com/dailypay", "company": "DailyPay", "slug": "dailypay"},
]

SMARTRECRUITERS_BOARDS: list[dict] = [
    {"url": "https://jobs.smartrecruiters.com/AJBell1", "company": "AJ Bell", "slug": "AJBell1"},
    {"url": "https://jobs.smartrecruiters.com/CPPInvestmentsInvestissementsRPC", "company": "CPP Investments", "slug": "CPPInvestmentsInvestissementsRPC"},
    {"url": "https://jobs.smartrecruiters.com/esureGroup", "company": "Esure", "slug": "esureGroup"},
    {"url": "https://jobs.smartrecruiters.com/EvelynPartners", "company": "Evelyn Partners", "slug": "EvelynPartners"},
    {"url": "https://jobs.smartrecruiters.com/Octopus1", "company": "Octopus", "slug": "Octopus1"},
    {"url": "https://jobs.smartrecruiters.com/Together", "company": "Together", "slug": "Together"},
    {"url": "https://jobs.smartrecruiters.com/Visa", "company": "Visa", "slug": "Visa"},
    {"url": "https://jobs.smartrecruiters.com/Vitol", "company": "Vitol", "slug": "Vitol"},
]

WORKABLE_BOARDS: list[dict] = [
    {"url": "https://apply.workable.com/castle-trust", "company": "Castle Trust Bank", "slug": "castle-trust"},
    {"url": "https://apply.workable.com/caxton/", "company": "Caxton Associates", "slug": "caxton"},
    {"url": "https://apply.workable.com/davy", "company": "Davy", "slug": "davy"},
    {"url": "https://apply.workable.com/hayfin-capital-management", "company": "Hayfin", "slug": "hayfin-capital-management"},
    {"url": "https://apply.workable.com/homeprotect", "company": "Homeprotect", "slug": "homeprotect"},
    {"url": "https://apply.workable.com/insight-investment", "company": "Insight Investment", "slug": "insight-investment"},
    {"url": "https://apply.workable.com/moneyfarm", "company": "Moneyfarm", "slug": "moneyfarm"},
    {"url": "https://apply.workable.com/onyx-capital-group", "company": "Onyx Capital Group", "slug": "onyx-capital-group"},
    {"url": "https://apply.workable.com/pension-services-corporation-limited", "company": "Pension Insurance Corporation", "slug": "pension-services-corporation-limited"},
    {"url": "https://apply.workable.com/vortexa", "company": "Vortexa", "slug": "vortexa"},
    {"url": "https://apply.workable.com/zego", "company": "Zego", "slug": "zego"},
    {"url": "https://apply.workable.com/capula-investment-management-ltd", "company": "Capula Investment Management", "slug": "capula-investment-management-ltd"},
]

EIGHTFOLD_BOARDS: list[dict] = [
    {"url": "https://aexp.eightfold.ai/careers", "company": "American Express"},
    {"url": "https://bnymellon.eightfold.ai/careers", "company": "BNY Mellon"},
    {"url": "https://mlp.eightfold.ai/careers", "company": "Millennium"},
    {"url": "https://morganstanley.eightfold.ai/careers", "company": "Morgan Stanley"},
    {"url": "https://morganstanley.eightfold.ai/careers", "company": "Morgan Stanley & Co. International Plc"},
]

SUCCESSFACTORS_BOARDS: list[dict] = [
    {"url": "https://career2.successfactors.eu/career?company=mizuhoba01", "company": "Mizuho Financial Group"},
    {"url": "https://career8.successfactors.com/career?company=MoodysProd", "company": "Moody's"},
    {"url": "https://career4.successfactors.com/career?company=natgridProd", "company": "National Grid"},
    {"url": "https://career5.successfactors.eu/career?company=banquepict", "company": "Pictet"},
    {"url": "https://career2.successfactors.eu/career?company=royallondo", "company": "Royal London"},
    {"url": "https://career2.successfactors.eu/career?company=standardch", "company": "Standard Chartered"},
    {"url": "https://career2.successfactors.eu/career?company=tsbukprod", "company": "TSB Bank"},
    {"url": "https://career5.successfactors.eu/career?company=AZGROUPPROD", "company": "Allianz"},
]

GENERIC_BROWSER_BOARDS: list[dict] = [
    {"url": "https://careers.7im.co.uk/vacancies", "company": "7IM"},
    {"url": "https://www.werkenbijabnamro.nl/en/vacancies/search/clearing", "company": "ABN AMRO"},
    {"url": "https://accelerant.ai/careers/", "company": "Accelerant Insurance UK Limited"},
    {"url": "https://www.accredited.com/careers", "company": "Accredited Insurance (UK) Limited"},
    {"url": "https://careers.acrisure.international/jobs", "company": "Acrisure"},
    {"url": "https://addepar.com/careers", "company": "Addepar"},
    {"url": "https://www.admiraljobs.co.uk/", "company": "Admiral"},
    {"url": "https://careers.adyen.com/", "company": "Adyen"},
    {"url": "https://www.affinitywatercareers.co.uk/jobs", "company": "Affinity Water"},
    {"url": "https://mytalent.csod.com/ux/ats/careersite/2/home", "company": "Ageas"},
    {"url": "https://careers.and-e.uk/jobs", "company": "Aioi Nissay Dowa Insurance UK Limited"},
    {"url": "https://www.alrayanbank.co.uk/jobs-and-careers/view-vacancies", "company": "Al Rayan Bank"},
    {"url": "https://www.alanboswell.com/careers/", "company": "Alan Boswell Group"},
    {"url": "https://aldermore.current-vacancies.com/Careers/Aldermore_vacancy_search_page-3181", "company": "Aldermore Bank"},
    {"url": "https://careers.allianz.com/global/en", "company": "Allianz"},
    {"url": "https://jobs.aib.ie/aib/go/SearchAllJobs/9605800/", "company": "Allied Irish Banks"},
    {"url": "https://www.allstate.jobs/job-search-results/", "company": "Allstate"},
    {"url": "https://ally.avature.net/careers", "company": "Ally Invest"},
    {"url": "https://alphafx.bamboohr.com/careers", "company": "Alpha"},
    {"url": "https://www.alphacrestcapital.com/careers", "company": "AlphaCrest Capital Management"},
    {"url": "https://adyne.com/employment.html", "company": "Alphadyne"},
    {"url": "https://www.linkedin.com/company/ambac/jobs/", "company": "Ambac Assurance UK Limited"},
    {"url": "https://jobs.amundi.com/", "company": "Amundi Asset Management"},
    {"url": "https://www.ancora.net/careers", "company": "Ancora Advisors"},
    {"url": "https://jobs.aon.com/jobs", "company": "Aon"},
    {"url": "https://careers.apexfintechsolutions.com/?size=n_5_n", "company": "Apex Fintech Solutions"},
    {"url": "https://careers.aqr.com/?size=n_5_n", "company": "AQR Capital Management (Europe) LLP"},
    {"url": "https://careers.arag.co.uk/vacancies", "company": "ARAG"},
    {"url": "https://careers.arbuthnotlatham.co.uk/vacancies/vacancy-search-results.aspx", "company": "Arbuthnot Latham"},
    {"url": "https://jobs.aspen.co/", "company": "Aspen Insurance"},
    {"url": "https://jobs.assurant.com/en/jobs", "company": "Assurant"},
    {"url": "https://assuredpartners.co.uk/jobs", "company": "AssuredPartners"},
    {"url": "https://www.atombank.co.uk/careers/", "company": "Atom Bank"},
    {"url": "https://careers.atradius.com/en/vacancies", "company": "Atradius"},
    {"url": "https://www.atrium-uw.com/opportunities/", "company": "Atrium"},
    {"url": "https://aventumhr.my.salesforce-sites.com/Recruit/fRecruit__ApplyJobList", "company": "Aventum"},
    {"url": "https://careers.axa.com/careers-home/jobs", "company": "AXA"},
    {"url": "https://peoplespartnership.co.uk/careers/current-vacancies/", "company": "B & C E Insurance Limited"},
    {"url": "https://peoplespartnership.my.salesforce-sites.com/recruit/fRecruit__ApplyJobList", "company": "B&CE"},
    {"url": "https://jobs.dayforcehcm.com/briley/CANDIDATEPORTAL", "company": "B. Riley"},
    {"url": "https://bacb.teamtailor.com/jobs", "company": "BACB"},
    {"url": "https://bambusdev.my.site.com/s/", "company": "Balyasny"},
    {"url": "https://careers.bankofamerica.com/en-us/job-search?ref=search&search=getAllJobs&rows=10&start=0", "company": "Bank of America"},
    {"url": "https://careers.bankofireland.com/jobs", "company": "Bank of Ireland"},
    {"url": "https://www.bankoflondon.com/join-our-team", "company": "Bank of London"},
    {"url": "https://search.jobs.barclays/", "company": "Barclays"},
    {"url": "https://www.bathbuildingsociety.co.uk/your-society/careers/current-vacancies/", "company": "Bath Investment & Building Society"},
    {"url": "https://careers.beaufort.group/jobs/Careers", "company": "Beaufort Insurance Company Limited"},
    {"url": "https://careers.beazley.com/jobs", "company": "Beazley"},
    {"url": "https://careers.benefactgroup.com/jobs", "company": "Benefact Group"},
    {"url": "https://berenberg.avature.net/en_GB/careers", "company": "Berenberg"},
    {"url": "https://www.bhspecialty.com/career/#jobs", "company": "BERKSHIRE HATHAWAY INTERNATIONAL INSURANCE LIMITED"},
    {"url": "https://www.betterment.com/careers/current-openings?hsCtaTracking=4c4ba664-a1f6-44b8-af75-b78f3995731a%7C2262c0cc-5fe8-4928-a6b2-fe64c49ed9eb", "company": "Betterment"},
    {"url": "https://beverleybs.co.uk/about-us-careers/", "company": "Beverley Building Society"},
    {"url": "https://markerstudygroup.talosats-careers.com/all-vacancies", "company": "BGL Group"},
    {"url": "https://bhsf.livevacancies.co.uk/#/", "company": "BHSF Limited"},
    {"url": "https://billingfinance.co.uk/careers/", "company": "Billing Finance"},
    {"url": "https://bloomberg.avature.net/careers/SearchJobs/", "company": "Bloomberg"},
    {"url": "https://www.bluebay.com/en/careers/", "company": "BlueBay Asset Management"},
    {"url": "https://jobs.bmo.com/ca/en/search-results", "company": "BMO"},
    {"url": "https://group.bnpparibas/en/careers/all-job-offers?q=", "company": "BNP Paribas", "use_firefox": True},
    {"url": "https://www.bordertocoast.org.uk/current-vacancies/", "company": "Border to Coast Pension Partnership"},
    {"url": "https://boxoptions.com/employment/", "company": "BOX Exchange"},
    {"url": "https://bhsf.livevacancies.co.uk/#/", "company": "Bridge House Friendly Society"},
    {"url": "https://britpeople.my.salesforce-sites.com/recruit/fRecruit__ApplyJobList", "company": "Brit"},
    {"url": "https://trcgrouphr.my.salesforce-sites.com/recruit/fRecruit__ApplyJobList", "company": "BRITANNIA STEAM SHIP INSURANCE ASSOCIATION LIMITED(THE)"},
    {"url": "https://careers.british-business-bank.co.uk/", "company": "British Business Bank"},
    {"url": "https://www.britishfriendly.com/about-us/careers/", "company": "British Friendly Society Limited"},
    {"url": "https://isw.changeworknow.co.uk/bii/vms/e/careers/positions/dsu2_jMIXmXBQAtS_IoLfw", "company": "British International Investment"},
    {"url": "https://isw.changeworknow.co.uk/bii/vms/e/careers/search/new", "company": "Broadstone"},
    {"url": "https://brooksmacdonald.current-vacancies.com/", "company": "Brooks Macdonald"},
    {"url": "https://www.cloudonlinerecruitment.co.uk/bspokegroup/Vacancy.aspx", "company": "Bspoke Group"},
    {"url": "https://www.bucksbs.co.uk/careers/", "company": "Buckinghamshire Building Society"},
    {"url": "https://jobs.bunge.com/search/", "company": "Bunge"},
    {"url": "https://www.caisgroup.com/careers", "company": "CAIS"},
    {"url": "https://ccbank.co.uk/about-us/careers/", "company": "Cambridge & Counties Bank"},
    {"url": "https://api.occupop.com/api/jobs-frame/ZIDaaVzxcfy3qsqhvs4i5JcOrzfU3TdJ38p4Vay2TjiRSRxAVc?&visibility=external&fields=title,type,location,sector", "company": "Cambridge Building Society"},
    {"url": "https://www.capco.com/Careers/Job-Search", "company": "Capco"},
    {"url": "https://jobs.capitalone.co.uk/", "company": "Capital One"},
    {"url": "https://jobs.carfinance247.co.uk/vacancies", "company": "Carfinance 247"},
    {"url": "https://www.cargill.com/careers", "company": "Cargill"},
    {"url": "https://carlyle.avature.net/externalcareers", "company": "Carlyle"},
    {"url": "https://jobs.dayforcehcm.com/cathaybank/CANDIDATEPORTAL", "company": "Cathay Bank"},
    {"url": "https://careers.cboe.com/us/en/search-results", "company": "Cboe Global Markets"},
    {"url": "https://www.ccla.co.uk/careers/", "company": "CCLA"},
    {"url": "https://portfoliojobs.cerberus.com/jobs", "company": "Cerberus"},
    {"url": "https://jobs.cfm.com/", "company": "CFM"},
    {"url": "https://www.charitybank.org/careers/", "company": "Charity Bank"},
    {"url": "https://www.schwabjobs.com/search-jobs", "company": "Charles Schwab"},
    {"url": "https://www.charlestaylor.com/en/careers/vacancies/", "company": "Charles Taylor"},
    {"url": "https://www.cinctive.com/", "company": "Cinctive Capital Management"},
    {"url": "https://www.citadel.com/careers/open-opportunities/", "company": "Citadel"},
    {"url": "https://www.citadel.com/careers/open-opportunities/", "company": "Citadel Securities"},
    {"url": "https://jobs.citi.com/", "company": "Citigroup"},
    {"url": "https://jobs.citizensbank.com/", "company": "Citizens"},
    {"url": "https://closebrothers.current-vacancies.com/Careers/Close%20Brothers%20VSP-1616", "company": "Close Brothers"},
    {"url": "https://www.cls-group.com/people/your-career/jobs", "company": "CLS Group"},
    {"url": "https://www.co-operativebankjobs.co.uk/vacancies/vacancy-search-results.aspx", "company": "Co-operative Bank"},
    {"url": "https://careers.cofcointernational.com/search/?q=&locationsearch=", "company": "COFCO International"},
    {"url": "https://collercapital-1660725598.teamtailor.com/jobs", "company": "Coller Capital"},
    {"url": "https://careers.ameriprise.com/search-jobs/", "company": "Columbia Threadneedle Investments"},
    {"url": "https://jobs.commerzbank.com/index.php?ac=search_result&search_criterion_channel%5B%5D=12", "company": "Commerzbank"},
    {"url": "https://www.cornishmutual.co.uk/join-our-team/", "company": "Cornish Mutual"},
    {"url": "https://www.coventrycareers.co.uk/vacancies/vacancy-search-results.aspx", "company": "Coventry Building Society"},
    {"url": "https://careers.manulife.com/global/en/search-results", "company": "CQS"},
    {"url": "https://jobs.ca-cib.com/", "company": "Credit Agricole"},
    {"url": "https://cumberland.current-vacancies.com/Careers/Cumberland-vacancy-search-page-3211", "company": "Cumberland Building Society"},
    {"url": "https://current.com/careers/", "company": "Current"},
    {"url": "https://www.cvc.com/careers/", "company": "CVC"},
    {"url": "https://careers.cynergybank.co.uk/jobs", "company": "Cynergy Bank"},
    {"url": "https://www.deshaw.com/careers", "company": "D. E. Shaw"},
    {"url": "https://www.davidsonkempner.com/careers/", "company": "Davidson Kempner"},
    {"url": "https://recruitment.developmentbank.wales/Careers/Careers-Dev-Bank-3441?SiteID=11231", "company": "Development Bank of Wales"},
    {"url": "https://draxgroup.csod.com/ux/ats/careersite/11/home", "company": "Drax Group"},
    {"url": "https://www.drw.com/work-at-drw/listings?filterType=country&value=United+Kingdom?filterType=country&value=United+Kingdom", "company": "DRW"},
    {"url": "https://www.dudleybuildingsociety.co.uk/about-us/careers/current-roles/", "company": "Dudley Building Society"},
    {"url": "https://www.esbs.co.uk/careers/", "company": "Earl Shilton Building Society"},
    {"url": "https://jobs.ebrd.com/search/?createNewAlert=false&q=&locationsearch=", "company": "EBRD"},
    {"url": "https://www.ecology.co.uk/careers/", "company": "Ecology Building Society"},
    {"url": "https://jobs.ecotricity.co.uk/vacancies/vacancy-search-results.aspx", "company": "Ecotricity"},
    {"url": "https://careers.edfenergy.com/jobs?q=&options=&page=1&la=0&lo=0&lr=20", "company": "EDF Energy"},
    {"url": "https://www.eislercapital.com/careers", "company": "Eisler Capital"},
    {"url": "https://www.jobtrain.co.uk/enwl/Home/Job?what=risk&longitude=0&latitude=0&distance=&where=", "company": "Electricity North West"},
    {"url": "https://www.ellington.com/careers", "company": "Ellington"},
    {"url": "https://cwan.com/company/careers/#openings", "company": "Enfusion"},
    {"url": "https://careers.enstargroup.com/search-our-jobs", "company": "Enstar Group"},
    {"url": "https://eqtgroup.com/careers", "company": "EQT"},
    {"url": "https://evolutionmoneyltd.livevacancies.co.uk/#/", "company": "Evolution Money"},
    {"url": "https://jobs.exxonmobil.com/ExxonMobil/search/?createNewAlert=false&q=&locationsearch=&optionsFacetsDD_department=&optionsFacetsDD_shifttype=&optionsFacetsDD_country=", "company": "ExxonMobil"},
    {"url": "https://genre.csod.com/ux/ats/careersite/2/home", "company": "Faraday"},
    {"url": "https://careers.fexco.com/#filter=p_web_site_id%3D4473%26p_published_to%3DWWW%26p_language%3DDEFAULT%26p_direct%3DY%26p_format%3DMOBILE%26p_include_exclude_from_list%3DN%26p_search%3D", "company": "Fexco"},
    {"url": "https://fidelisigcareers.azurewebsites.net/", "company": "Fidelis"},
    {"url": "https://jobs.fidelity.com/en/jobs/?search=&origin=global&lat=&lng=", "company": "Fidelity"},
    {"url": "https://www.firstcentralcareers.com/jobs", "company": "First Central Insurance & Technology Group"},
    {"url": "https://careers.fisglobal.com/us/en/search-results", "company": "FIS"},
    {"url": "https://careers.fiserv.com/us/en/search-results", "company": "Fiserv"},
    {"url": "https://franklintempleton.wd5.myworkdayjobs.com/Primary-External-1?_gl=1*1njnutk*_ga*MTAyOTcyMjIwNy4xNzc1NzU1MzMw*_ga_15V8ZZDP8Z*czE3NzU3NTUzMjkkbzEkZzEkdDE3NzU3NTUzNDAkajQ5JGwwJGgw", "company": "Franklin Templeton"},
    {"url": "https://fscs.current-vacancies.com/", "company": "FSCS"},
    {"url": "https://www.furnessbs.co.uk/about-us/working-with-us", "company": "Furness Building Society"},
    {"url": "https://www.gcmgrosvenor.com/open-positions/", "company": "GCM Grosvenor"},
    {"url": "https://ghanainternationalbank-1644937212.teamtailor.com/jobs?split_view=true&query=", "company": "GHIB"},
    {"url": "https://careers.gic.com.sg/search/?createNewAlert=falseu0026amp;q=u0026amp;optionsFacetsDD_title=u0026amp;optionsFacetsDD_department=u0026amp;optionsFacetsDD_customfield2=Permanentu0026amp;locationsearch=", "company": "GIC"},
    {"url": "https://www.glencore.com/careers/jobs", "company": "Glencore"},
    {"url": "https://higher.gs.com/results?&page=1&sort=RELEVANCE", "company": "Goldman Sachs"},
    {"url": "https://hamilton.bamboohr.com/careers", "company": "Hamilton"},
    {"url": "https://jobs.handelsbanken.co.uk/jobs", "company": "Handelsbanken"},
    {"url": "https://www.thehanley.co.uk/careers", "company": "Hanley Economic Building Society"},
    {"url": "https://www.harpendenbs.co.uk/about-us/working-for-us/vacancies/", "company": "Harpenden Building Society"},
    {"url": "https://www.hartreepartners.com/careers", "company": "Hartree Partners"},
    {"url": "https://ukcareers.hdi.global/", "company": "HDI Global Specialty"},
    {"url": "https://hinckleyandrugby.teamtailor.com/jobs", "company": "Hinckley & Rugby Building Society"},
    {"url": "https://www.hitachienergy.com/careers/open-jobs/", "company": "Hitachi Energy"},
    {"url": "https://hodgebank.co.uk/careers/", "company": "Hodge"},
    {"url": "https://portal.careers.hsbc.com/careers", "company": "HSBC"},
    {"url": "https://www.icapitalnetwork.com/careers/", "company": "iCapital"},
    {"url": "https://icbccareers.resourcesolutions.com/gold/iapply/index.cfm?event=jobs.search", "company": "ICBC"},
    {"url": "https://careers.ice.com/jobs", "company": "ICE"},
    {"url": "https://www.imc.com/us/search-careers", "company": "IMC"},
    {"url": "https://careers.ing.com/en/search-jobs", "company": "ING"},
    {"url": "https://inigohr.my.salesforce-sites.com/Recruit/fRecruit__ApplyJobList?uid=", "company": "Inigo"},
    {"url": "https://jobs.insightpartners.com/jobs", "company": "Insight Partners"},
    {"url": "https://jobs.intesasanpaolo.com/search/?createNewAlert=false&q=&locationsearch=&optionsFacetsDD_facility=Intesa+Sanpaolo+and+other+Companies&optionsFacetsDD_country=&optionsFacetsDD_department=Audit%2C+Risk%2C+Compliance+%26+Legal&optionsFacetsDD_customfield1=Experienced", "company": "Intesa Sanpaolo"},
    {"url": "https://careers.investec.co.uk/jobs/vacancy/find/results/", "company": "Investec"},
    {"url": "https://iqeq.com/careers/vacancies/", "company": "IQ-EQ"},
    {"url": "https://life-careers.com/canadalife/search/?createNewAlert=false&q=&locationsearch=&optionsFacetsDD_department=&optionsFacetsDD_country=&optionsFacetsDD_facility=", "company": "Irish Life Group"},
    {"url": "https://careers.isio.com/jobs", "company": "Isio"},
    {"url": "https://www.janestreet.com/join-jane-street/open-roles/?type=experienced-candidates&location=london", "company": "Jane Street"},
    {"url": "https://jobs.janushenderson.com/search/?createNewAlert=false&q=&optionsFacetsDD_customfield3=&optionsFacetsDD_country=&optionsFacetsDD_department=", "company": "Janus Henderson"},
    {"url": "https://jeragm.recruiterpal.com/career/jobs", "company": "JERA Global Markets"},
    {"url": "https://jtcgroup.csod.com/ux/ats/careersite/4/home", "company": "JTC Group"},
    {"url": "https://www-webflow.jumptrading.com/hr/experienced-candidates", "company": "Jump Trading"},
    {"url": "https://fs-4345.my.salesforce-sites.com/recruit/fRecruit__ApplyJobList?portal=KS+Agency+Portal", "company": "King Street Capital Management"},
    {"url": "https://jobs.deel.com/klarna", "company": "Klarna"},
    {"url": "https://koch.avature.net/en_US/careers", "company": "Koch Industries"},
    {"url": "https://careers.lancashiregroup.com/vacancies#js-careers-jobs-block", "company": "Lancashire Group"},
    {"url": "https://www.lansdownepartners.com/london/careers/", "company": "Lansdowne Partners"},
    {"url": "https://lazard-careers.tal.net/vx/lang-en-GB/mobile-0/appcentre-1/brand-4/candidate/jobboard/vacancy/2/adv/?", "company": "Lazard"},
    {"url": "https://www.leedsbuildingsocietyjobs.co.uk/jobs/vacancy/find/results/", "company": "Leeds Building Society"},
    {"url": "https://www.leekbs.co.uk/careers/our-current-vacancies/", "company": "Leek Building Society"},
    {"url": "https://careers.legalandgeneral.com/jobs?q=&options=&page=1", "company": "Legal & General"},
    {"url": "https://makers.lemonade.com/", "company": "Lemonade"},
    {"url": "https://www.lgpscentral.co.uk/careers/index.html#vacancies", "company": "LGPS Central"},
    {"url": "https://libertymutual1.avature.net/LibertyCareers", "company": "Liberty Specialty Markets"},
    {"url": "https://careers.lightsourcebp.com/go/View-All-Jobs/8639602/?_gl=1*jfma38*_gcl_au*MTQ2OTkzMzQ1My4xNzc1OTI5NzMz", "company": "Lightsource BP"},
    {"url": "https://lightspeed.com/about-us/careers", "company": "Lightspeed"},
    {"url": "https://linde.csod.com/ux/ats/careersite/20/home", "company": "Linde"},
    {"url": "https://www.liv-ex.com/careers/", "company": "Liv-ex"},
    {"url": "https://lockton-career.talent-soft.com/accueil.aspx?LCID=2057", "company": "Lockton"},
    {"url": "https://jobs.dayforcehcm.com/en-US/loomissayles/CANDIDATEPORTAL", "company": "Loomis Sayles"},
    {"url": "https://lppicareers.localpensionspartnership.org.uk/", "company": "LPP"},
    {"url": "https://jobsportal.lv.com/vacancies", "company": "LV="},
    {"url": "https://workforcenow.adp.com/mascsr/default/mdf/recruitment/recruitment.html?cid=e36fcc0f-b0a6-4b8e-ba8b-1fe996800059&ccId=19000101_000001&type=JS&lang=en_US", "company": "MacKay Shields"},
    {"url": "https://recruitment.macquarie.com/en_US/careers/SearchJobs/?listFilterMode=1&jobRecordsPerPage=9&", "company": "Macquarie"},
    {"url": "https://www.mako.com/opportunities/job-listing", "company": "Mako Group"},
    {"url": "https://many-group.com/careers/opportunities/", "company": "ManyGroup"},
    {"url": "https://www.markel.com/careers", "company": "Markel International Insurance Company Limited"},
    {"url": "https://markerstudygroup.talosats-careers.com", "company": "Markerstudy Group"},
    {"url": "https://mhbs.co.uk/vacancies/", "company": "Market Harborough Building Society"},
    {"url": "https://www.marketaxess.com/careers", "company": "MarketAxess"},
    {"url": "https://cezanneondemand.intervieweb.it/marlboroughgroup/jobs", "company": "Marlborough"},
    {"url": "https://phh.tbe.taleo.net/phh03/ats/careers/v2/searchResults?org=ELLINGTONMGMTGRP&cws=37", "company": "Marsden Building Society"},
    {"url": "https://careers.marshmclennan.com/global/en", "company": "Marsh McLennan"},
    {"url": "https://www.mwam.com/careers/", "company": "Marshall Wace"},
    {"url": "https://www.mwam.com/careers", "company": "Marshall Wace LLP"},
    {"url": "https://www.themelton.co.uk/", "company": "Melton Mowbray Building Society"},
    {"url": "https://mercuria.com/careers/", "company": "Mercuria"},
    {"url": "https://careers.bankofamerica.com/en-us", "company": "Merrill"},
    {"url": "https://careers.bankofamerica.com/", "company": "Merrill Lynch International"},
    {"url": "https://jobs.metlife.com/", "company": "MetLife"},
    {"url": "https://metrobank.avature.net/amazingcareers", "company": "Metro Bank"},
    {"url": "https://www.mcbankny.com/careers/", "company": "Metropolitan Commercial Bank"},
    {"url": "https://www.mfs.com/en-us/careers.html", "company": "MFS Investment Management"},
    {"url": "https://miaxglobal.com/careers", "company": "MIAX"},
    {"url": "https://www.miller-insurance.com/careers/current-vacancies/", "company": "Miller"},
    {"url": "https://www.mizuhogroup.com/americas/careers", "company": "Mizuho"},
    {"url": "https://monbs.current-vacancies.com/Jobs/Advert", "company": "Monmouthshire Building Society"},
    {"url": "https://monumentbanklimited.careers.hibob.com/jobs", "company": "Monument"},
    {"url": "https://www.monumentregroup.com/vacancies/", "company": "Monument Re"},
    {"url": "https://www.moomoo.com/us/support/topic4_730", "company": "moomoo"},
    {"url": "https://www.moonpay.com/careers", "company": "MoonPay"},
    {"url": "https://www.moorecap.com/", "company": "Moore Capital Management"},
    {"url": "https://www.mosaicinsurance.com/careers/", "company": "Mosaic Insurance"},
    {"url": "https://recruitment.mo.co.uk/vacancies", "company": "Motability Operations"},
    {"url": "https://aldermore.current-vacancies.com/Careers/Aldermore_vacancy_search_page-3181", "company": "motonovo finance"},
    {"url": "https://careers.msci.com/", "company": "MSCI"},
    {"url": "https://www.mubadalacapital.com/careers", "company": "Mubadala Capital"},
    {"url": "https://www.mudrickcapital.com/", "company": "Mudrick Capital Management"},
    {"url": "https://careerstore.munichre.com/", "company": "Munich Re"},
    {"url": "https://www.natixis.com/natixis/jcms/lpaz5_68570/en/careers", "company": "Natixis CIB"},
    {"url": "https://www.newbury.co.uk/", "company": "Newbury Building Society"},
    {"url": "https://emea3.recruitmentplatform.com/syndicated/lay/jsoutputinitrapido.cfm", "company": "NFU Mutual"},
    {"url": "https://www.nhbc.co.uk/careers/job-opportunities", "company": "NHBC"},
    {"url": "https://www.ninetyone.com/en/united-kingdom/careers", "company": "Ninety One UK Limited"},
    {"url": "https://careers.nomura.com/Nomura/search/?q=&sortColumn=referencedate&sortDirection=desc", "company": "Nomura"},
    {"url": "https://www.nomura.com/careers/", "company": "Nomura International Plc"},
    {"url": "https://northumbrianwater.current-vacancies.com/Jobs/Advert", "company": "Northumbrian Water Group"},
    {"url": "https://www.thenottingham.com/", "company": "Nottingham Building Society"},
    {"url": "https://careers.tiaa.org/", "company": "Nuveen"},
    {"url": "https://www.cmegroup.com/careers.html", "company": "NYMEX"},
    {"url": "https://careers.intercontinentalexchange.com/", "company": "NYSE"},
    {"url": "https://www.nyse.com/careers", "company": "NYSE American"},
    {"url": "https://www.ocorian.com/", "company": "Ocorian"},
    {"url": "https://jobs.lever.co/octoenergy", "company": "Octopus Energy"},
    {"url": "https://www.odey.com/", "company": "Odey Asset Management"},
    {"url": "https://www.ofi.com/careers.html", "company": "Olam"},
    {"url": "https://onefamily.current-vacancies.com/Jobs/Advert", "company": "OneFamily"},
    {"url": "https://www.onex.com/careers", "company": "Onex"},
    {"url": "https://optiver.com/working-at-optiver/career-opportunities/", "company": "Optiver"},
    {"url": "https://careers-osb.icims.com/jobs", "company": "OSB Group"},
    {"url": "https://www.hioscar.com/careers", "company": "Oscar Health"},
    {"url": "https://www.otcmarkets.com/careers", "company": "OTC Markets Group"},
    {"url": "https://careers.ovo.com/", "company": "Ovo Energy"},
    {"url": "https://www.oxam.com/join-us/", "company": "Oxford Asset Management"},
    {"url": "https://psam.com/", "company": "P Schoenfeld Asset Management"},
    {"url": "https://pagaya.com/careers/", "company": "Pagaya"},
    {"url": "https://careers.paragonbankinggroup.co.uk/vacancies", "company": "Paragon Banking Group"},
    {"url": "https://jobs.partnersgroup.com/", "company": "Partners Group"},
    {"url": "https://www.partnersand.com/resources/", "company": "Partners&"},
    {"url": "https://www.paulsonco.com/careers/", "company": "Paulson & Co."},
    {"url": "https://www.paxos.com/careers/", "company": "Paxos"},
    {"url": "https://careers.pypl.com/home/", "company": "PayPal"},
    {"url": "https://www.pdtpartners.com/join-us/", "company": "PDT Partners"},
    {"url": "https://www.penrithbs.co.uk/", "company": "Penrith Building Society"},
    {"url": "https://ppf.current-vacancies.com/Jobs/FeedLink", "company": "Pension Protection Fund"},
    {"url": "https://www.pepper-advantage.com/available-jobs", "company": "Pepper Advantage"},
    {"url": "https://www.pwpartners.com/careers", "company": "Perella Weinberg Partners"},
    {"url": "https://www.persq.com/careers", "company": "Pershing Square"},
    {"url": "https://www.persq.com/careers/", "company": "Pershing Square Capital Management"},
    {"url": "https://www.pfgl.co.uk/careers/vacancies-jobs/", "company": "Perspective"},
    {"url": "https://jobs.prudential.com/", "company": "PGIM"},
    {"url": "https://www.pinebridge.com/en/careers", "company": "PineBridge"},
    {"url": "https://careers.pinnaclepetuk.com", "company": "Pinnacle Pet UK"},
    {"url": "https://careers.point72.com/", "company": "Point72"},
    {"url": "https://www.polarcapital.co.uk/careers", "company": "Polar Capital LLP"},
    {"url": "https://www.poolre.co.uk/careers/", "company": "Pool Reinsurance Company Limited"},
    {"url": "https://ppf.current-vacancies.com/Jobs", "company": "PPF"},
    {"url": "https://www.premiermiton.com/about-us/people/vacancies/", "company": "Premier Miton Investors"},
    {"url": "https://careers.principal.com/", "company": "Principal Asset Management"},
    {"url": "https://isw.changeworknow.co.uk/principality/vms/e/careers/search/new", "company": "Principality Building Society"},
    {"url": "https://www.quantbottech.com/", "company": "Quantbot Technologies"},
    {"url": "https://www.qube-rt.com/careers", "company": "Qube Research & Technologies"},
    {"url": "https://careers.quintet.com/BrownShipley", "company": "Quintet"},
    {"url": "https://ramp.com/careers", "company": "Ramp"},
    {"url": "https://yourcareer.rathbones.com/", "company": "Rathbones"},
    {"url": "https://www.raymondjames.com/careers", "company": "Raymond James"},
    {"url": "https://jobs.rbc.com/ca/en", "company": "RBC"},
    {"url": "https://jobs.rbc.com/", "company": "RBC Global Asset Management"},
    {"url": "https://redmayne.current-vacancies.com/Jobs/Advert", "company": "Redmayne Bentley"},
    {"url": "https://www.rentec.com/Careers.action?index=true", "company": "Renaissance Technologies"},
    {"url": "https://www.renre.com/careers/", "company": "RenaissanceRe"},
    {"url": "https://therightmortgage.co.uk/careers/", "company": "Right Mortgage"},
    {"url": "https://www.rsml.co.uk/careers/", "company": "RiverStone"},
    {"url": "https://www.rlicorp.com/careers", "company": "RLI"},
    {"url": "https://www.rockco.com/careers/", "company": "Rockefeller Capital Management"},
    {"url": "https://rokoscapital.com/careers/", "company": "Rokos Capital Management"},
    {"url": "https://jobs.hedgehoginsurance.com/jobs", "company": "Rostella"},
    {"url": "https://www.rsainsurance.co.uk/careers/uk-job-description/", "company": "RSA"},
    {"url": "https://www.ruffer.co.uk/careers", "company": "Ruffer LLP"},
    {"url": "https://careers.spglobal.com/", "company": "S&P Global"},
    {"url": "https://www.saffronbs.co.uk/about/about-us/careers#vacancies-target", "company": "Saffron Building Society"},
    {"url": "https://careerssearch.saga.co.uk/jobs", "company": "Saga"},
    {"url": "https://www.santanderbank.com/personal/about-us/careers", "company": "Santander US"},
    {"url": "https://www.schonfeld.com/careers", "company": "Schonfeld"},
    {"url": "https://jobs.scotiabank.com/", "company": "Scotiabank"},
    {"url": "https://www.scottishbs.co.uk/", "company": "Scottish Building Society"},
    {"url": "https://scottishfriendly.jobs.people-first.com/jobs", "company": "Scottish Friendly"},
    {"url": "https://www.sculptor.com/", "company": "Sculptor Capital Management"},
    {"url": "https://careers.securetrustbank.com/vacancies", "company": "Secure Trust Bank"},
    {"url": "https://career55.sapsf.eu/career", "company": "SEFE"},
    {"url": "https://www.segantii.com/", "company": "Segantii Capital Management"},
    {"url": "https://www.seopa.com/careers/data-scientist/", "company": "Seopa"},
    {"url": "https://www.careers.severntrent.com/", "company": "Severn Trent"},
    {"url": "https://careers.shawbrook.co.uk/en/jobs", "company": "Shawbrook"},
    {"url": "https://jobs.shell.com/", "company": "Shell"},
    {"url": "https://careers.sig.com/", "company": "SIG"},
    {"url": "https://www.silverlake.com/careers/", "company": "Silver Lake"},
    {"url": "https://jobs.lever.co/simplybusiness", "company": "Simply Business"},
    {"url": "https://careers.simplyhealth.co.uk/vacancies", "company": "Simplyhealth"},
    {"url": "https://jobs.jobvite.com/siriuspoint", "company": "SiriusPoint"},
    {"url": "https://www.sixthstreet.com/careers/", "company": "Sixth Street"},
    {"url": "https://careersemea.smbcgroup.com/", "company": "SMBC"},
    {"url": "https://careers.so.energy/jobs", "company": "So Energy"},
    {"url": "https://careers.societegenerale.com/en/job-offers/", "company": "Societe Generale"},
    {"url": "https://careers.societegenerale.com/en/", "company": "Societe Generale International Limited"},
    {"url": "https://www.sofi.com/careers/", "company": "SoFi"},
    {"url": "https://careers.somersetbridgeinsurance.com/vacancies/", "company": "Somerset Bridge Group"},
    {"url": "https://www.sompo-intl.com/careers", "company": "Sompo"},
    {"url": "https://www.squarepoint-capital.com/open-opportunities", "company": "Squarepoint"},
    {"url": "https://www.squarepoint-capital.com/careers", "company": "Squarepoint Capital"},
    {"url": "https://careers.ssctech.com/", "company": "SS&C"},
    {"url": "https://careers.sse.com/jobs", "company": "SSE"},
    {"url": "https://sjp.csod.com/ux/ats/careersite/4/home", "company": "St James's Place"},
    {"url": "https://www.standardbank.com/sbg/standard-bank-group/careers/apply/jobs", "company": "Standard Bank"},
    {"url": "https://www.stepstonegroup.com/careers/", "company": "StepStone Group"},
    {"url": "https://www.stifel.com/careers", "company": "Stifel"},
    {"url": "https://jobs.dayforcehcm.com/en-US/stonefleming/CANDIDATEPORTAL/jobs", "company": "Stonehage Fleming"},
    {"url": "https://www.stonepeak.com/careers/", "company": "Stonepeak"},
    {"url": "https://careers.successionwealth.co.uk/", "company": "Succession Wealth"},
    {"url": "https://www.suffolkbuildingsociety.co.uk/", "company": "Suffolk Building Society"},
    {"url": "https://careers.sig.com/", "company": "Susquehanna"},
    {"url": "https://www.swansea-bs.co.uk/cs/c/", "company": "Swansea Building Society"},
    {"url": "https://careers.swissre.com/", "company": "Swiss Re"},
    {"url": "https://www.taconiccap.com/careers", "company": "Taconic"},
    {"url": "https://www.taconiccap.com/", "company": "Taconic Capital Advisors"},
    {"url": "https://tastytrade.com/careers", "company": "tastytrade"},
    {"url": "https://jobs.td.com/", "company": "TD Bank"},
    {"url": "https://jobs.td.com/", "company": "TD Securities / TD Cowen"},
    {"url": "https://www.teachersbuildingsociety.co.uk/", "company": "Teachers Building Society"},
    {"url": "https://tescoinsuranceandmoneyservices.avature.net/careers", "company": "Tesco Insurance"},
    {"url": "https://careers.everywhen.co.uk/jobs", "company": "The Ardonagh Group"},
    {"url": "https://www.chorleybs.co.uk/", "company": "The Chorley and District Building Society"},
    {"url": "https://cumberland.current-vacancies.com/Jobs/Advert", "company": "The Cumberland"},
    {"url": "https://www.thehartford.com/careers", "company": "The Hartford"},
    {"url": "https://www.mansfieldbs.co.uk/", "company": "The Mansfield Building Society"},
    {"url": "https://careers.thenottingham.com/vacancies", "company": "The Nottingham"},
    {"url": "https://apply.theopenworkpartnership.com/vacancies", "company": "The Openwork Partnership"},
    {"url": "https://www.srbs.co.uk/", "company": "The Stafford Railway Building Society"},
    {"url": "https://www.thirdpoint.com/careers", "company": "Third Point"},
    {"url": "https://www.thomabravo.com/careers", "company": "Thoma Bravo"},
    {"url": "https://my.corehr.com/pls/coreportal_tmmsp/erq_jobspec_version_4.display_form", "company": "Thomas Miller"},
    {"url": "https://www.tigerglobal.com/careers/", "company": "Tiger Global"},
    {"url": "https://www.tigerglobal.com/", "company": "Tiger Global Management"},
    {"url": "https://www.timefinance.com/careers/", "company": "Time Finance"},
    {"url": "https://www.thetipton.co.uk/about-us/join-our-team/", "company": "Tipton & Coseley Building Society"},
    {"url": "https://www.thetipton.co.uk/", "company": "Tipton and Coseley Building Society"},
    {"url": "https://jobs.lever.co/titanwh", "company": "Titan"},
    {"url": "https://www.toscafund.com/", "company": "ToscaFund"},
    {"url": "https://www.toscafund.com/", "company": "Toscafund Asset Management LLP"},
    {"url": "https://jobs.totalenergies.com/en_US/careers/", "company": "TotalEnergies"},
    {"url": "https://www.tradestation.com/careers/", "company": "TradeStation"},
    {"url": "https://www.tradeweb.com/careers/", "company": "Tradeweb"},
    {"url": "https://www.trafigura.com/careers/", "company": "Trafigura"},
    {"url": "https://www.jobtrain.co.uk/transact/", "company": "Transact"},
    {"url": "https://careers.travelers.com", "company": "Travelers"},
    {"url": "https://www.triodos.co.uk/vacancies/", "company": "Triodos Bank"},
    {"url": "https://www.tudor.com/careers", "company": "Tudor Capital Europe"},
    {"url": "https://www.tudor.com/careers", "company": "Tudor Investment Corporation"},
    {"url": "https://careers.twosigma.com/", "company": "Two Sigma"},
    {"url": "https://jobs.ubs.com/TGnewUI/Search/home/HomeWithPreLoad", "company": "UBS"},
    {"url": "https://www.ukfinance.org.uk/careers/", "company": "UK Finance"},
    {"url": "https://careers.ukpowernetworks.co.uk/", "company": "UK Power Networks"},
    {"url": "https://www.utbank.co.uk/grow-with-utb/", "company": "United Trust Bank"},
    {"url": "https://www.unitedutilities.com/corporate/careers/details/", "company": "United Utilities Group"},
    {"url": "https://uss.appellia.com/positions/", "company": "USS"},
    {"url": "https://utmosthr.my.salesforce-sites.com/recruit/fRecruit__ApplyJobList", "company": "Utmost International"},
    {"url": "https://www.valley.com/careers", "company": "Valley Bank"},
    {"url": "https://www.vaneck.com/us/en/careers/", "company": "VanEck"},
    {"url": "https://vanquisbank.current-vacancies.com/Jobs/Advert", "company": "Vanquis Banking Group"},
    {"url": "https://www.veritionfund.com/careers/", "company": "Verition Fund Management"},
    {"url": "https://www.thevernon.co.uk/", "company": "Vernon Building Society"},
    {"url": "https://www.vidabank.co.uk/our-group/careers/current-opportunities/", "company": "Vida Bank"},
    {"url": "https://www.vikingglobal.com/", "company": "Viking Global Investors"},
    {"url": "https://careers.virginmoney.com/", "company": "Virgin Money"},
    {"url": "https://www.virtu.com/careers/", "company": "Virtu Financial"},
    {"url": "https://www.vistaequitypartners.com/careers/", "company": "Vista Equity Partners"},
    {"url": "https://careers.vistra.com/", "company": "Vistra"},
    {"url": "https://recruit.vitality.co.uk/vacancies", "company": "Vitality"},
    {"url": "https://www.voleon.com/careers/", "company": "Voleon"},
    {"url": "https://www.wafra.com/careers/", "company": "Wafra"},
    {"url": "https://wcgplc.bamboohr.com/careers", "company": "Walker Crips"},
    {"url": "https://www.warburgpincus.com/careers/", "company": "Warburg Pincus"},
    {"url": "https://careers.websteronline.com/", "company": "Webster Bank"},
    {"url": "https://www.webullcorp.com/careers", "company": "Webull"},
    {"url": "https://www.wedbush.com/careers/", "company": "Wedbush"},
    {"url": "https://careers.wesleyan.co.uk/vacancies", "company": "Wesleyan"},
    {"url": "https://www.jobtrain.co.uk/westbromcareers/", "company": "West Brom"},
    {"url": "https://www.westbrom.co.uk/", "company": "West Bromwich Building Society"},
    {"url": "https://www.wisdomtree.com/careers", "company": "WisdomTree"},
    {"url": "https://ce0382li.webitrent.com/ce0382li_webrecruitment", "company": "XPS"},
    {"url": "https://www.xtxmarkets.com/careers/", "company": "XTX Markets"},
    {"url": "https://www.yieldstreet.com/careers", "company": "Yieldstreet"},
    {"url": "https://www.yorkcapital.com/", "company": "York Capital Management"},
    {"url": "https://ybscareers.co.uk", "company": "Yorkshire Building Society"},
    {"url": "https://mycareers.yorkshirewater.com/", "company": "Yorkshire Water"},
    {"url": "https://careers.zenobe.com/jobs", "company": "Zenobe"},
    {"url": "https://www.careers.zurich.com", "company": "Zurich"},
    {"url": "https://phh.tbe.taleo.net/phh03/ats/careers/v2/searchResults?org=ELLINGTONMGMTGRP&cws=37", "company": "The Marsden"},
]

LEVER_BOARDS: list[dict] = [
    {"company": "Anchorage Digital", "slug": "anchorage", "url": "https://jobs.lever.co/anchorage"},
    {"company": "Plaid", "slug": "plaid", "url": "https://jobs.lever.co/plaid"},
]

ICIMS_BOARDS: list[dict] = [
    {"company": "Ameriprise Financial", "slug": "careers-ameriprise", "url": "https://careers-ameriprise.icims.com/jobs"},
    {"company": "AmTrust Specialty Limited", "slug": "careers-amtrustgroup", "url": "https://careers-amtrustgroup.icims.com/jobs/intro?mobile=false&width=1150&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240"},
    {"company": "Bank of China USA", "slug": "careers-bocusa", "url": "https://careers-bocusa.icims.com/jobs/search?hashed=-625889845&mobile=false&width=1536&height=500&bga=true&needsRedirect=false&jan1offset=0&jun1offset=60"},
    {"company": "Dalriada", "slug": "dalriadacareers-3173", "url": "https://dalriadacareers-3173.icims.com/jobs/intro?hashed=-625975121&mobile=false&width=1000&height=500&bga=true&needsRedirect=false&jan1offset=0&jun1offset=60"},
    {"company": "East West Bank", "slug": "careers-eastwestbank", "url": "https://careers-eastwestbank.icims.com/jobs/intro?mobile=false&width=1270&height=500&bga=true&needsRedirect=false&jan1offset=0&jun1offset=60"},
    {"company": "Gallagher", "slug": "ukjobs-ajg", "url": "https://ukjobs-ajg.icims.com/jobs"},
    {"company": "Guardian Life", "slug": "careers-guardianlife", "url": "https://careers-guardianlife.icims.com/jobs"},
    {"company": "Lincoln Financial", "slug": "careers-lfg", "url": "https://careers-lfg.icims.com/jobs"},
    {"company": "Lord Abbett", "slug": "careers-lordabbett", "url": "https://careers-lordabbett.icims.com/jobs/search?hashed=-435678259&mobile=false&width=600&height=500&bga=true&needsRedirect=false&jan1offset=0&jun1offset=60"},
    {"company": "New York Life", "slug": "careers-newyorklife", "url": "https://careers-newyorklife.icims.com/jobs"},
    {"company": "OneAmerica", "slug": "careers-oneamerica", "url": "https://careers-oneamerica.icims.com/jobs"},
    {"company": "Pacific Life", "slug": "careers-pacificlife", "url": "https://careers-pacificlife.icims.com/jobs"},
    {"company": "Principal Financial Group", "slug": "careers-principal", "url": "https://careers-principal.icims.com/jobs"},
    {"company": "Protective Life", "slug": "careers-protective", "url": "https://careers-protective.icims.com/jobs"},
    {"company": "StoneX", "slug": "uk-stonex", "url": "https://uk-stonex.icims.com/jobs"},
    {"company": "Transamerica", "slug": "careers-transamerica", "url": "https://careers-transamerica.icims.com/jobs"},
    {"company": "Unum Group", "slug": "careers-unum", "url": "https://careers-unum.icims.com/jobs"},
    {"company": "Marathon Asset Management", "slug": "careers-marathonfund", "url": "https://careers-marathonfund.icims.com/jobs/search"},
    {"company": "Voya Financial", "slug": "careers-voya", "url": "https://careers-voya.icims.com/jobs"},
    {"company": "Berkley", "slug": "careers-berkley", "url": "https://careers-berkley.icims.com/jobs"},
]

HIBOB_BOARDS: list[dict] = [
    {"url": "https://aspectcapital-94a5ce.careers.hibob.com/", "company": "Aspect Capital"},
    {"url": "https://darlingtonbui-837c76.careers.hibob.com/", "company": "Darlington Building Society"},
]

SELECTMINDS_BOARDS: list[dict] = [
    {"url": "https://ajg.referrals.selectminds.com/jobs/", "company": "Arthur J. Gallagher"},
]

SILKROAD_BOARDS: list[dict] = [
    {"url": "https://opco-openhire.silkroad.com/", "company": "Oppenheimer & Co."},
]

TALEO_BOARDS: list[dict] = [
    {"url": "https://voyacareers.taleo.net/careersection/2/jobsearch.ftl", "company": "Voya Investment Management"},
]

# ---------------------------------------------------------------------------
# Adzuna
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Pinpoint boards — JSON API at {url}/en/postings.json
# ---------------------------------------------------------------------------
PINPOINT_BOARDS: list[dict] = [
    {"url": "https://careers.auroraer.com/en/postings", "company": "Aurora Energy Research"},
    {"url": "https://cfc.pinpointhq.com/en/postings", "company": "CFC"},
    {"url": "https://chetwood-bank.pinpointhq.com/en/postings", "company": "Chetwood Bank"},
    {"url": "https://compregroup.pinpointhq.com/en/postings", "company": "Compre"},
    {"url": "https://davies.pinpointhq.com/en/postings", "company": "Davies"},
    {"url": "https://networkplus.pinpointhq.com/en/postings", "company": "Network Plus"},
    {"url": "https://poloworks.pinpointhq.com/en/postings", "company": "PoloWorks"},
]

ADZUNA_BOARDS: list[dict] = [
    {"company": "Adzuna", "url": "https://www.adzuna.co.uk", "search_terms": ["risk", "quant", "quantitative", "compliance", "strats", "pricing", "algorithmic", "audit", "legal", "cyber", "trader", "trading"], "countries": ["gb", "us", "ca", "de", "fr", "nl", "sg"], "max_pages": 10},
]

CORESIGNAL_BOARDS: list[dict] = [
    {
        "company": "Coresignal",
        "url": "https://api.coresignal.com/cdapi/v2/job_multi_source",
        "search_terms": [
            "risk", "quant", "quantitative", "compliance", "audit",
            "legal", "cyber", "financial crime", "trader", "trading",
        ],
        "countries": ["United Kingdom"],
        "max_per_term": 100,  # IDs fetched per search_term × country combo
        "request_delay": 0.1,  # seconds between requests (18/sec cap on search)
    },
]

REED_BOARDS: list[dict] = [
    {"company": "Reed", "url": "https://www.reed.co.uk", "search_terms": ["risk", "quant", "quantitative", "compliance", "strats", "pricing", "algorithmic", "audit", "legal", "cyber", "trader", "trading"], "locations": ["London", "Manchester", "Birmingham", "Edinburgh", "Glasgow", "Bristol", "Leeds", "Dublin", "Belfast", "Cardiff"]},
]

EFINANCIALCAREERS_BOARDS: list[dict] = [
    {"company": "eFinancialCareers", "url": "https://www.efinancialcareers.com", "search_terms": ["risk", "quant", "quantitative", "compliance", "strats", "pricing", "algorithmic", "audit", "legal", "cyber", "trader", "trading"]},
]

GOOGLE_JOBS_BOARDS: list[dict] = [
    {"company": "Google Jobs", "url": "https://www.google.com/search?q=jobs", "search_terms": ["risk manager finance", "credit risk analyst", "market risk", "quantitative analyst finance", "compliance officer financial services", "audit manager financial services", "cyber security financial services", "trader fixed income", "portfolio manager"], "locations": [["London, United Kingdom", "UK"], ["New York, NY, United States", "USA"], ["Toronto, Ontario, Canada", "Canada"], ["Frankfurt, Germany", "Germany"], ["Paris, France", "France"], ["Amsterdam, Netherlands", "Netherlands"], ["Dublin, Ireland", "Ireland"], ["Zurich, Switzerland", "Switzerland"], ["Singapore", "Singapore"], ["Hong Kong", "Hong Kong"]], "max_pages_per_query": 3},
]

RECRUITEE_BOARDS: list[dict] = [
    {"url": "https://equalsmoney.recruitee.com/", "company": "Equals Money", "slug": "equalsmoney"},
]

PERSONIO_BOARDS: list[dict] = [
    {"url": "https://dm-financial.jobs.personio.com/", "company": "DM Financial", "slug": "dm-financial"},
]

JAZZHR_BOARDS: list[dict] = [
    {"url": "https://cure.applytojob.com/apply/jobs/", "company": "CURE International", "slug": "cure"},
    {"url": "https://resourcepro.applytojob.com/apply/jobs/", "company": "Resource Pro", "slug": "resourcepro"},
]

BEAMERY_BOARDS: list[dict] = [
    {"url": "https://flows.beamery.eu/grantthornton/trainee-ryi", "company": "Grant Thornton", "slug": "grantthornton"},
]

PHENOM_BOARDS: list[dict] = [
    {"url": "https://careers.phenom.com/global/en/home", "company": "Phenom", "slug": "phenom"},
]

CLEARCOMPANY_BOARDS: list[dict] = [
    {"url": "https://jobs.clearcompany.com/careers/", "company": "ClearCompany", "slug": "clearcompany"},
]

ADP_BOARDS: list[dict] = [
    {"url": "https://jobs.adp.com/en/jobs/", "company": "ADP", "slug": "adp"},
]

INFOR_BOARDS: list[dict] = [
    {"url": "https://careers.infor.com/en_US/89/SearchJobs", "company": "Infor", "slug": "infor"},
]

# ---------------------------------------------------------------------------
# Search keywords (used by API scrapers that support server-side search)
# ---------------------------------------------------------------------------
SEARCH_TERMS = [
    "risk", "quant", "quantitative", "compliance", "strats", "pricing", "algorithmic",
    "audit", "legal", "cyber", "trader", "trading",
]
