
"""
Central configuration: all 551 unique job board URLs, platform routing,
and pre-parsed Workday board structs.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from urllib.parse import urlparse


# ---------------------------------------------------------------------------
# Workday board struct + parser
# ---------------------------------------------------------------------------

@dataclass
class WorkdayBoard:
    board_url: str
    tenant: str
    shard: str      # e.g. "wd3", "wd5"
    site_path: str  # e.g. "RBS", "2"
    company: str = ""

    @property
    def api_url(self) -> str:
        return (
            f"https://{self.tenant}.{self.shard}.myworkdayjobs.com"
            f"/wday/cxs/{self.tenant}/{self.site_path}/jobs"
        )

    @property
    def domain(self) -> str:
        return f"{self.tenant}.{self.shard}.myworkdayjobs.com"


def _parse_workday_url(url: str, company: str = "") -> WorkdayBoard:
    parsed = urlparse(url)
    host = parsed.netloc.lower()
    parts = [p for p in parsed.path.split("/") if p]

    if "myworkdayjobs.com" in host:
        # Pattern A: {tenant}.{shard}.myworkdayjobs.com/en-US/{site}
        subdomain_parts = host.split(".")
        tenant = subdomain_parts[0]
        shard = subdomain_parts[1]
        # site_path is the last non-locale part of the path
        site_path = parts[-1] if parts else tenant
    else:
        # Pattern B: wd1.myworkdaysite.com/en-US/recruiting/{tenant}/{site}
        shard = host.split(".")[0]  # e.g. "wd1"
        # path looks like: ["en-US", "recruiting", "wf", "WellsFargoJobs"]
        tenant = parts[2] if len(parts) > 2 else parts[-2]
        site_path = parts[3] if len(parts) > 3 else parts[-1]

    return WorkdayBoard(
        board_url=url,
        tenant=tenant,
        shard=shard,
        site_path=site_path,
        company=company,
    )


# ---------------------------------------------------------------------------
# All 551 board URLs grouped by platform
# ---------------------------------------------------------------------------

WORKDAY_BOARDS: list[WorkdayBoard] = [
    # --- existing ---
    _parse_workday_url("https://athene.wd5.myworkdayjobs.com/en-US/Apollo_Careers", "Apollo"),
    _parse_workday_url("https://lloyds.wd3.myworkdayjobs.com/en-US/Lloyds-of-London", "Lloyd's"),
    _parse_workday_url("https://wd1.myworkdaysite.com/en-US/recruiting/wf/WellsFargoJobs", "Wells Fargo"),
    _parse_workday_url("https://citi.wd5.myworkdayjobs.com/en-US/2", "Citi"),
    _parse_workday_url("https://ukib.wd3.myworkdayjobs.com/en-US/UKIB", "UK Infrastructure Bank"),
    _parse_workday_url("https://rbs.wd3.myworkdayjobs.com/en-US/RBS", "NatWest Group"),
    _parse_workday_url("https://sedgwick.wd1.myworkdayjobs.com/en-US/Sedgwick", "Sedgwick"),
    _parse_workday_url("https://bpinternational.wd3.myworkdayjobs.com/en-US/bpCareers", "BP"),
    _parse_workday_url("https://tmhcc.wd108.myworkdayjobs.com/en-US/External", "Tokio Marine HCC"),
    _parse_workday_url("https://mastercard.wd1.myworkdayjobs.com/en-US/CorporateCareers", "Mastercard"),
    _parse_workday_url("https://mgpru.wd3.myworkdayjobs.com/en-US/mandgprudential", "M&G Prudential"),
    _parse_workday_url("https://bbva.wd3.myworkdayjobs.com/en-US/BBVA", "BBVA"),
    _parse_workday_url("https://ghr.wd1.myworkdayjobs.com/en-US/lateral-emea", "Goldman Sachs"),
    _parse_workday_url("https://rabobank.wd3.myworkdayjobs.com/en-US/jobs", "Rabobank"),
    _parse_workday_url("https://awg.wd3.myworkdayjobs.com/en-US/aw", "Anglian Water"),
    _parse_workday_url("https://cibc.wd3.myworkdayjobs.com/en-US/search", "CIBC"),
    _parse_workday_url("https://blackrock.wd1.myworkdayjobs.com/en-US/BlackRock_Professional", "BlackRock"),
    _parse_workday_url("https://statestreet.wd1.myworkdayjobs.com/en-US/Global", "State Street"),
    # --- new ---
    _parse_workday_url("https://abrdn.wd3.myworkdayjobs.com/en-US/abrdn", "abrdn"),
    _parse_workday_url("https://absa.wd3.myworkdayjobs.com/en-US/ABSAcareersite", "ABSA"),
    _parse_workday_url("https://aegislondon.wd3.myworkdayjobs.com/en-US/Careers", "AEGIS London"),
    _parse_workday_url("https://aig.wd1.myworkdayjobs.com/en-US/aig", "AIG"),
    _parse_workday_url("https://archgroup.wd1.myworkdayjobs.com/en-US/Careers", "Arch"),
    _parse_workday_url("https://aresmgmt.wd1.myworkdayjobs.com/en-US/External", "Ares"),
    _parse_workday_url("https://aviva.wd1.myworkdayjobs.com/en-US/External", "Aviva"),
    _parse_workday_url("https://axiscapital.wd1.myworkdayjobs.com/en-US/axiscareers", "AXIS"),
    _parse_workday_url("https://ayvens.wd3.myworkdayjobs.com/en-US/AyvensCareers", "Ayvens"),
    _parse_workday_url("https://aztecgroup.wd103.myworkdayjobs.com/en-US/External", "Aztec Group"),
    _parse_workday_url("https://bailliegifford.wd3.myworkdayjobs.com/en-US/BaillieGiffordCareers", "Baillie Gifford"),
    _parse_workday_url("https://barings.wd1.myworkdayjobs.com/en-US/Barings", "Barings"),
    _parse_workday_url("https://bbinsurance.wd1.myworkdayjobs.com/en-US/Careers_Europe", "Brown & Brown"),
    _parse_workday_url("https://blackstone.wd1.myworkdayjobs.com/en-US/Blackstone_Campus_Careers", "Blackstone"),
    _parse_workday_url("https://brookfield.wd5.myworkdayjobs.com/en-US/brookfield", "Brookfield"),
    _parse_workday_url("https://capgroup.wd1.myworkdayjobs.com/en-US/capitalgroupcareers", "Capital Group"),
    _parse_workday_url("https://cba.wd3.myworkdayjobs.com/en-US/CommBank_Careers", "Commonwealth Bank"),
    _parse_workday_url("https://centrica.wd3.myworkdayjobs.com/en-US/Centrica", "Centrica"),
    _parse_workday_url("https://cgg.wd103.myworkdayjobs.com/en-US/viridiencareers", "Viridien"),
    _parse_workday_url("https://challenger.wd3.myworkdayjobs.com/en-US/Challenger_Careers", "Challenger"),
    _parse_workday_url("https://chaucergroup.wd3.myworkdayjobs.com/en-US/chaucer_group_careers", "Chaucer"),
    _parse_workday_url("https://chevron.wd5.myworkdayjobs.com/en-US/jobs", "Chevron"),
    _parse_workday_url("https://cigna.wd5.myworkdayjobs.com/en-US/cignacareers", "Cigna"),
    _parse_workday_url("https://cmegroup.wd1.myworkdayjobs.com/en-US/cme_careers", "CME Group"),
    _parse_workday_url("https://cna.wd1.myworkdayjobs.com/en-US/CNAHardy", "CNA Hardy"),
    _parse_workday_url("https://corpay.wd103.myworkdayjobs.com/en-US/Ext_001", "Corpay"),
    _parse_workday_url("https://db.wd3.myworkdayjobs.com/de-DE/DBWebsite", "Deutsche Bank"),
    _parse_workday_url("https://dlg.wd3.myworkdayjobs.com/en-US/DLGCAREERS", "Direct Line"),
    _parse_workday_url("https://domesticandgeneral.wd3.myworkdayjobs.com/en-US/DeGCareers", "Domestic & General"),
    _parse_workday_url("https://edftrading.wd1.myworkdayjobs.com/en-US/EDFTrading", "EDF"),
    _parse_workday_url("https://endurance.wd103.myworkdayjobs.com/en-US/SompoInternational", "Sompo International"),
    _parse_workday_url("https://eonnext.wd3.myworkdayjobs.com/en-US/EON_Next_Careers", "E.ON Next"),
    _parse_workday_url("https://fil.wd3.myworkdayjobs.com/en-US/001", "Fidelity International"),
    _parse_workday_url("https://franklintempleton.wd5.myworkdayjobs.com/en-US/Primary-External-1", "Franklin Templeton"),
    _parse_workday_url("https://godirect.wd5.myworkdayjobs.com/en-US/voya_jobs", "Voya Financial"),
    _parse_workday_url("https://harbourvest.wd5.myworkdayjobs.com/en-US/HVP", "HarbourVest"),
    _parse_workday_url("https://hargreaveslansdown.wd3.myworkdayjobs.com/en-US/HargreavesLansdown", "Hargreaves Lansdown"),
    _parse_workday_url("https://hastingsdirect.wd3.myworkdayjobs.com/en-US/external_careers", "Hastings Direct"),
    _parse_workday_url("https://hiscox.wd3.myworkdayjobs.com/en-US/Hiscox_External_Site", "Hiscox"),
    _parse_workday_url("https://hkex.wd3.myworkdayjobs.com/en-US/HKEXCareerPage", "HKEX"),
    _parse_workday_url("https://hl.wd1.myworkdayjobs.com/en-US/Lateral", "Houlihan Lokey"),
    _parse_workday_url("https://hrhub.wd3.myworkdayjobs.com/en-US/Euronext_Career_Page", "Euronext"),
    _parse_workday_url("https://hyperiongrp.wd3.myworkdayjobs.com/en-US/hyperion_external", "Howden Group Holdings"),
    _parse_workday_url("https://iberdrola.wd3.myworkdayjobs.com/en-US/Iberdrola", "Iberdrola"),
    _parse_workday_url("https://icg.wd3.myworkdayjobs.com/en-US/external_careers", "ICG"),
    _parse_workday_url("https://intrum.wd3.myworkdayjobs.com/en-US/External", "Intrum"),
    _parse_workday_url("https://invesco.wd1.myworkdayjobs.com/en-US/IVZ", "Invesco"),
    _parse_workday_url("https://jupiteram.wd3.myworkdayjobs.com/en-US/jupiter_careers", "Jupiter"),
    _parse_workday_url("https://just.wd3.myworkdayjobs.com/en-US/JUST_External", "Just"),
    _parse_workday_url("https://krgroup.wd3.myworkdayjobs.com/en-US/KR_Group", "KeyGroup"),
    _parse_workday_url("https://lseg.wd3.myworkdayjobs.com/en-US/Careers", "LSEG"),
    _parse_workday_url("https://markelcorp.wd5.myworkdayjobs.com/en-US/GlobalCareers", "Markel"),
    _parse_workday_url("https://mfs.wd1.myworkdayjobs.com/en-US/MFS-Careers", "MFS"),
    _parse_workday_url("https://moelis.wd1.myworkdayjobs.com/en-US/Experienced-Hires", "Moelis & Company"),
    _parse_workday_url("https://morningstar.wd5.myworkdayjobs.com/en-US/Americas", "Morningstar"),
    _parse_workday_url("https://msamlin.wd3.myworkdayjobs.com/en-US/MSAmlinCareers", "MS Amlin"),
    _parse_workday_url("https://mtb.wd5.myworkdayjobs.com/en-US/MTB", "M&T Bank"),
    _parse_workday_url("https://mufgub.wd3.myworkdayjobs.com/en-US/MUFG-Careers", "MUFG"),
    _parse_workday_url("https://muzinich.wd5.myworkdayjobs.com/en-US/muzinichcareers", "Muzinich & Co."),
    _parse_workday_url("https://nasdaq.wd1.myworkdayjobs.com/en-US/Global_External_Site", "Nasdaq"),
    _parse_workday_url("https://nb.wd1.myworkdayjobs.com/en-US/NBCareers", "Neuberger Berman"),
    _parse_workday_url("https://newcastle.wd3.myworkdayjobs.com/en-US/NBSCareers", "Newcastle Building Society"),
    _parse_workday_url("https://newday.wd3.myworkdayjobs.com/en-US/NewDay", "NewDay"),
    _parse_workday_url("https://nibcatwork.wd3.myworkdayjobs.com/en-US/External", "NIBC Bank"),
    _parse_workday_url("https://ntrs.wd1.myworkdayjobs.com/en-US/northerntrust", "Northern Trust"),
    _parse_workday_url("https://oaktree.wd1.myworkdayjobs.com/en-US/Oaktree", "Oaktree"),
    _parse_workday_url("https://oldmutual.wd3.myworkdayjobs.com/en-US/Old_Mutual_Careers", "Old Mutual"),
    _parse_workday_url("https://pacificlife.wd1.myworkdayjobs.com/en-US/PacificLifeReCareers", "Pacific Life Re"),
    _parse_workday_url("https://perpetual.wd3.myworkdayjobs.com/en-US/JOHCM_External", "J O Hambro Capital Management"),
    _parse_workday_url("https://perpetual.wd3.myworkdayjobs.com/en-US/external", "Perpetual"),
    _parse_workday_url("https://pibgroup.wd3.myworkdayjobs.com/en-US/PIB", "PIB Group"),
    _parse_workday_url("https://pimco.wd1.myworkdayjobs.com/en-US/pimco-careers", "PIMCO"),
    _parse_workday_url("https://pjtpartners.wd1.myworkdayjobs.com/en-US/Careers", "PJT Partners"),
    _parse_workday_url("https://progleasing.wd5.myworkdayjobs.com/en-US/ProgLeasingCareers", "Progressive Leasing"),
    _parse_workday_url("https://qbe.wd3.myworkdayjobs.com/en-US/QBE-Careers", "QBE Insurance"),
    _parse_workday_url("https://quilter.wd3.myworkdayjobs.com/en-US/External-Career-Site", "Quilter"),
    _parse_workday_url("https://railpen.wd3.myworkdayjobs.com/en-US/Railpen", "Railpen"),
    _parse_workday_url("https://rothschildandco.wd3.myworkdayjobs.com/en-US/RothschildAndCo_Lateral", "Rothschild & Co"),
    _parse_workday_url("https://ryansg.wd5.myworkdayjobs.com/en-US/Ryan_Specialty_Career_Site", "Ryan Specialty"),
    _parse_workday_url("https://santander.wd3.myworkdayjobs.com/en-US/SantanderCareers", "Santander"),
    _parse_workday_url("https://scottishwater.wd3.myworkdayjobs.com/en-US/External_Careers", "Scottish Water"),
    _parse_workday_url("https://seic.wd1.myworkdayjobs.com/en-US/SEI_Global_Services", "SEI"),
    _parse_workday_url("https://shell.wd3.myworkdayjobs.com/en-US/ShellCareers", "Shell Global"),
    _parse_workday_url("https://skipton.wd3.myworkdayjobs.com/en-US/Careers-Skipton", "Skipton Building Society"),
    _parse_workday_url("https://spw.wd3.myworkdayjobs.com/en-US/spw_careers", "Schroders Personal Wealth"),
    _parse_workday_url("https://starrcompanies.wd1.myworkdayjobs.com/en-US/careers", "Starr Companies"),
    _parse_workday_url("https://td.wd3.myworkdayjobs.com/en-US/TD_Bank_Careers", "TD"),
    _parse_workday_url("https://theapexgroup.wd3.myworkdayjobs.com/en-US/apexgroupcareers", "APEX"),
    _parse_workday_url("https://tokiomarinekiln.wd3.myworkdayjobs.com/en-US/TMK_Careers", "Tokio Marine Kiln"),
    _parse_workday_url("https://tp.wd107.myworkdayjobs.com/en-US/TP-ICAP", "TP ICAP"),
    _parse_workday_url("https://transamerica.wd5.myworkdayjobs.com/en-US/AEGONAM", "Aegon Asset Management"),
    _parse_workday_url("https://transamerica.wd5.myworkdayjobs.com/en-US/AUK_JobSite", "Aegon"),
    _parse_workday_url("https://travelex.wd107.myworkdayjobs.com/en-US/TravelexCareers", "Travelex"),
    _parse_workday_url("https://troweprice.wd5.myworkdayjobs.com/en-US/TRowePriceInternational", "T. Rowe Price"),
    _parse_workday_url("https://unum.wd1.myworkdayjobs.com/en-US/External", "Unum"),
    _parse_workday_url("https://usbank.wd1.myworkdayjobs.com/en-US/US_Bank_Careers", "US Bank"),
    _parse_workday_url("https://vanguard.wd5.myworkdayjobs.com/en-US/vanguard_external", "Vanguard"),
    _parse_workday_url("https://wd3.myworkdaysite.com/en-US/recruiting/brevanhoward/BH_ExternalCareers", "Brevan Howard"),
    _parse_workday_url("https://wd5.myworkdaysite.com/en-US/recruiting/everestre/careers", "Everest"),
    _parse_workday_url("https://wd5.myworkdaysite.com/en-US/recruiting/pru/Careers", "Prudential Financial"),
    _parse_workday_url("https://wellington.wd5.myworkdayjobs.com/en-US/External", "Wellington Management"),
    _parse_workday_url("https://wfscorp.wd5.myworkdayjobs.com/en-US/wfscareers", "World Fuel Services"),
]

ORACLE_BOARDS: list[dict] = [
    # --- existing ---
    {"url": "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "JPMorgan Chase"},
    {"url": "https://dnn.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/Nationwide", "company": "Nationwide"},
    {"url": "https://eoff.fa.em1.ukg.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "Bank of England"},
    {"url": "https://hdpc.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/LateralHiring", "company": "HDFC"},
    {"url": "https://eedu.fa.em3.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003", "company": "Willis Towers Watson"},
    {"url": "https://ebxr.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1", "company": "DTCC"},
    {"url": "https://fa-euxc-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1", "company": "CITCO"},
    {"url": "https://fa-enor-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX", "company": "Phoenix"},
    # --- new ---
    {"url": "https://don.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003", "company": "Euroclear"},
    {"url": "https://ebuu.fa.ap1.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX", "company": "Westpac Banking"},
    {"url": "https://ejjl.fa.ap1.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1", "company": "AustralianSuper"},
    {"url": "https://ejqi.fa.ocs.oraclecloud.eu/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "Danske Bank"},
    {"url": "https://ekbq.fa.em2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2", "company": "Schroders"},
    {"url": "https://enlc.fa.ap1.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "IFM Investors"},
    {"url": "https://fa-emkq-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX", "company": "Ascot"},
    {"url": "https://fa-eqai-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001", "company": "EFG"},
    {"url": "https://fa-errt-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001", "company": "SCOR"},
    {"url": "https://fa-evdq-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001", "company": "Computershare"},
    {"url": "https://fa-evdq-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/computersharecareers", "company": "Computershare"},
    {"url": "https://fa-ewgu-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_2001", "company": "Chubb"},
    {"url": "https://fa-exdv-saasfaprod1.fa.ocs.oraclecloud.com/hcmUI/CandidateExperience/en/sites/Careers", "company": "Westfield Specialty"},
    {"url": "https://hdfg.fa.em3.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX", "company": "Charles Stanley"},
    {"url": "https://hdow.fa.us6.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1003", "company": "BGC"},
    {"url": "https://hdpc.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CampusHiring", "company": "Goldman Sachs"},
]

GREENHOUSE_BOARDS: list[dict] = [
    # --- existing ---
    {"url": "https://job-boards.eu.greenhouse.io/mangroup/jobs", "company": "Man Group", "slug": "mangroup"},
    # --- new ---
    {"url": "https://boards.greenhouse.io/aztecgroup/jobs", "company": "Aztec Group", "slug": "aztecgroup"},
    {"url": "https://job-boards.eu.greenhouse.io/apollosyndicate1969/jobs", "company": "Apollo", "slug": "apollosyndicate1969"},
    {"url": "https://job-boards.eu.greenhouse.io/lhvuk/jobs", "company": "LHV", "slug": "lhvuk"},
    {"url": "https://job-boards.eu.greenhouse.io/policyexpert/jobs", "company": "Policy Expert", "slug": "policyexpert"},
    {"url": "https://job-boards.eu.greenhouse.io/srm/jobs", "company": "SRM", "slug": "srm"},
    {"url": "https://job-boards.eu.greenhouse.io/winton/jobs", "company": "Winton", "slug": "winton"},
    {"url": "https://job-boards.greenhouse.io/drweng/jobs", "company": "DRW Holdings", "slug": "drweng"},
    {"url": "https://job-boards.greenhouse.io/ibkr/jobs", "company": "Interactive Brokers", "slug": "ibkr"},
    {"url": "https://job-boards.greenhouse.io/mavensecuritiesholdingltd/jobs", "company": "Maven", "slug": "mavensecuritiesholdingltd"},
    {"url": "https://job-boards.greenhouse.io/pharomanagement/jobs", "company": "Pharo Management", "slug": "pharomanagement"},
    {"url": "https://job-boards.greenhouse.io/rothesaylife/jobs", "company": "Rothesay", "slug": "rothesaylife"},
    # --- fintechs (confirmed live 2026-04-01) ---
    {"url": "https://boards.greenhouse.io/stripe/jobs", "company": "Stripe", "slug": "stripe"},
    {"url": "https://boards.greenhouse.io/coinbase/jobs", "company": "Coinbase", "slug": "coinbase"},
    {"url": "https://boards.greenhouse.io/chime/jobs", "company": "Chime", "slug": "chime"},
    {"url": "https://boards.greenhouse.io/robinhood/jobs", "company": "Robinhood", "slug": "robinhood"},
    {"url": "https://boards.greenhouse.io/monzo/jobs", "company": "Monzo", "slug": "monzo"},
    {"url": "https://boards.greenhouse.io/brex/jobs", "company": "Brex", "slug": "brex"},
    {"url": "https://boards.greenhouse.io/marqeta/jobs", "company": "Marqeta", "slug": "marqeta"},
]

ASHBY_BOARDS: list[dict] = [
    # --- existing ---
    {"url": "https://jobs.ashbyhq.com/allica-bank", "company": "Allica Bank", "slug": "allica-bank"},
]

SMARTRECRUITERS_BOARDS: list[dict] = [
    # --- existing ---
    {"url": "https://jobs.smartrecruiters.com/Together", "company": "Together", "slug": "Together"},
    # --- new ---
    {"url": "https://jobs.smartrecruiters.com/AJBell1", "company": "AJ Bell", "slug": "AJBell1"},
    {"url": "https://jobs.smartrecruiters.com/CPPInvestmentsInvestissementsRPC", "company": "CPP Investments", "slug": "CPPInvestmentsInvestissementsRPC"},
    {"url": "https://jobs.smartrecruiters.com/EvelynPartners", "company": "Evelyn Partners", "slug": "EvelynPartners"},
    {"url": "https://jobs.smartrecruiters.com/Octopus1", "company": "Octopus", "slug": "Octopus1"},
    {"url": "https://jobs.smartrecruiters.com/Visa", "company": "Visa", "slug": "Visa"},
    {"url": "https://jobs.smartrecruiters.com/Vitol", "company": "Vitol", "slug": "Vitol"},
    {"url": "https://jobs.smartrecruiters.com/esureGroup", "company": "Esure", "slug": "esureGroup"},
]

WORKABLE_BOARDS: list[dict] = [
    # --- existing ---
    {"url": "https://apply.workable.com/hayfin-capital-management", "company": "Hayfin", "slug": "hayfin-capital-management"},
    # --- new ---
    {"url": "https://apply.workable.com/castle-trust", "company": "Castle Trust Bank", "slug": "castle-trust"},
    {"url": "https://apply.workable.com/davy", "company": "Davy", "slug": "davy"},
    {"url": "https://apply.workable.com/homeprotect", "company": "Homeprotect", "slug": "homeprotect"},
    {"url": "https://apply.workable.com/insight-investment", "company": "Insight Investment", "slug": "insight-investment"},
    {"url": "https://apply.workable.com/moneyfarm", "company": "Moneyfarm", "slug": "moneyfarm"},
    {"url": "https://apply.workable.com/onyx-capital-group", "company": "Onyx Capital Group", "slug": "onyx-capital-group"},
    {"url": "https://apply.workable.com/pension-services-corporation-limited", "company": "Pension Insurance Corporation", "slug": "pension-services-corporation-limited"},
    {"url": "https://apply.workable.com/vortexa", "company": "Vortexa", "slug": "vortexa"},
    {"url": "https://apply.workable.com/zego", "company": "Zego", "slug": "zego"},
]

EIGHTFOLD_BOARDS: list[dict] = [
    # --- existing ---
    {"url": "https://aexp.eightfold.ai/careers", "company": "American Express"},
    {"url": "https://morganstanley.eightfold.ai/careers", "company": "Morgan Stanley"},
    {"url": "https://bnymellon.eightfold.ai/careers", "company": "BNY Mellon"},
    # --- new ---
    {"url": "https://mlp.eightfold.ai/careers", "company": "Millennium"},
]

SUCCESSFACTORS_BOARDS: list[dict] = [
    # --- existing ---
    {"url": "https://career2.successfactors.eu/career?company=royallondo", "company": "Royal London"},
    {"url": "https://career2.successfactors.eu/career?company=standardch", "company": "Standard Chartered"},
    {"url": "https://career8.successfactors.com/career?company=MoodysProd", "company": "Moody's"},
    # --- new ---
    {"url": "https://career2.successfactors.eu/career?company=mizuhoba01", "company": "Mizuho Financial Group"},
    {"url": "https://career2.successfactors.eu/career?company=tsbukprod", "company": "TSB Bank"},
    {"url": "https://career4.successfactors.com/career?company=natgridProd", "company": "National Grid"},
    {"url": "https://career5.successfactors.eu/career?company=banquepict", "company": "Pictet"},
]

# All remaining custom boards — scraped via generic Playwright heuristic scraper
GENERIC_BROWSER_BOARDS: list[dict] = [
    # --- existing ---
    {"url": "https://careers.enstargroup.com/search-our-jobs", "company": "Enstar Group"},
    {"url": "https://careers.arbuthnotlatham.co.uk/vacancies", "company": "Arbuthnot Latham"},
    {"url": "https://www.nhbc.co.uk/careers/job-opportunities", "company": "NHBC"},
    {"url": "https://jobs.exxonmobil.com/ExxonMobil", "company": "ExxonMobil"},
    {"url": "https://careers.travelers.com", "company": "Travelers"},
    {"url": "https://jobs.ajg.com/ajg-home/jobs", "company": "Gallagher"},
    {"url": "https://www.allstate.jobs", "company": "Allstate"},
    {"url": "https://www.careers.zurich.com", "company": "Zurich"},
    {"url": "https://ppf.current-vacancies.com/Jobs", "company": "PPF"},
    {"url": "https://careers.axa.com/careers-home/jobs", "company": "AXA"},
    {"url": "https://www.lloydsbankinggroup.com/careers/job-search", "company": "Lloyds Banking Group"},
    {"url": "https://jobs.smartrecruiters.com/Together", "company": "Together"},  # also via API
    {"url": "https://careers.nomura.com/Nomura", "company": "Nomura"},
    {"url": "https://ybscareers.co.uk", "company": "Yorkshire Building Society"},
    {"url": "https://tescoinsuranceandmoneyservices.avature.net/careers", "company": "Tesco Insurance"},
    {"url": "https://metrobank.avature.net/amazingcareers", "company": "Metro Bank"},
    {"url": "https://www.coventrycareers.co.uk/vacancies", "company": "Coventry Building Society"},
    {"url": "https://careers.cynergybank.co.uk/jobs", "company": "Cynergy Bank"},
    {"url": "https://ce0602li.webitrent.com/ce0602li_webrecruitment", "company": "H & T PawnBrokers"},
    {"url": "https://search.jobs.barclays", "company": "Barclays"},
    {"url": "https://jobs.rbc.com/ca/en", "company": "RBC"},
    {"url": "https://www.standardbank.com/sbg/standard-bank-group/careers/apply/jobs", "company": "Standard Bank"},
    {"url": "https://collercapital-1660725598.teamtailor.com/jobs", "company": "Coller Capital"},
    {"url": "https://careers.shawbrook.co.uk/en/jobs", "company": "Shawbrook"},
    {"url": "https://careers.paragonbankinggroup.co.uk/vacancies", "company": "Paragon Banking Group"},
    {"url": "https://recruit.vitality.co.uk/vacancies", "company": "Vitality"},
    {"url": "https://markerstudygroup.talosats-careers.com", "company": "Markerstudy Group"},
    {"url": "https://careers.pinnaclepetuk.com", "company": "Pinnacle Pet UK"},
    {"url": "https://careers.zenobe.com/jobs", "company": "Zenobe"},
    {"url": "https://jobs.handelsbanken.co.uk/jobs", "company": "Handelsbanken"},
    {"url": "https://www.chathamfinancial.com/careers/jobs", "company": "Chatham Financial"},
    {"url": "https://bambusdev.my.site.com/s", "company": "Balyasny"},
    # --- new ---
    {"url": "https://agencycareers.nfumutual.co.uk/jobs", "company": "NFU Mutual"},
    {"url": "https://aldermore.current-vacancies.com/Jobs/Advert", "company": "Aldermore Bank"},
    {"url": "https://alphafx.bamboohr.com/careers", "company": "Alpha"},
    {"url": "https://alrayanbank.peoplehr.net/Pages/JobBoard/Opening.aspx", "company": "Al Rayan Bank"},
    {"url": "https://antaresglobal.com/jobs", "company": "Antares"},
    {"url": "https://anthesisgroup.pinpointhq.com/en/postings", "company": "Anthesis"},
    {"url": "https://api.occupop.com/shared", "company": "LGPS Central"},
    {"url": "https://apply.theopenworkpartnership.com/vacancies", "company": "The Openwork Partnership"},
    {"url": "https://applybe.com/charlestayloriframe/search/Vacancy/all/1", "company": "Charles Taylor"},
    {"url": "https://applybe.com/charlestayloriframe/search/Vacancy/all/2", "company": "Charles Taylor"},
    {"url": "https://applybe.com/charlestayloriframe/search/Vacancy/all/3", "company": "Charles Taylor"},
    {"url": "https://assuredpartners.co.uk/jobs", "company": "AssuredPartners"},
    {"url": "https://aztec.group/vacancy/jersey/6673387003/senior-regulatory-reporting-administrator", "company": "Aztec Group"},
    {"url": "https://aztec.group/vacancy/southampton/6526676003/senior-new-business-risk-analyst", "company": "Aztec Group"},
    {"url": "https://aztec.group/vacancy/southampton/6554458003/senior-new-business-risk-analyst", "company": "Aztec Group"},
    {"url": "https://aztec.group/vacancy/southampton/6564625003/junior-depositary-analyst", "company": "Aztec Group"},
    {"url": "https://bacb.teamtailor.com/jobs", "company": "BACB"},
    {"url": "https://berenberg.avature.net/en_GB/careers", "company": "Berenberg"},
    {"url": "https://bglgroup.taleo.net/careersection/bgl_external/jobdetail.ftl", "company": "BGL Group"},
    {"url": "https://billingfinance.peoplehr.net/Pages/JobBoard/Opening.aspx", "company": "Billing Finance"},
    {"url": "https://britpeople.my.salesforce-sites.com/recruit/fRecruit__ApplyJob", "company": "Brit"},
    {"url": "https://broadstonepeople.my.salesforce-sites.com/recruit/fRecruit__ApplyJob", "company": "Broadstone"},
    {"url": "https://brooksmacdonald.current-vacancies.com/Jobs/FeedLink", "company": "Brooks Macdonald"},
    {"url": "https://career55.sapsf.eu/career", "company": "SEFE"},
    {"url": "https://careers-berkley.icims.com/jobs", "company": "Berkley"},
    {"url": "https://careers-osb.icims.com/jobs", "company": "OSB Group"},
    {"url": "https://careers-uknordicswitz-berkley.icims.com/jobs", "company": "Berkley"},
    {"url": "https://careers.7im.co.uk/vacancies", "company": "7IM"},
    {"url": "https://careers.acrisure.international/jobs", "company": "Acrisure"},
    {"url": "https://careers.allianz.com/", "company": "Allianz"},
    {"url": "https://careers.allianz.com/global/en", "company": "Allianz"},
    {"url": "https://careers.ameriprise.com/search-jobs/r25_0000001169/investment-risk-analyst/", "company": "Columbia Threadneedle Investments"},
    {"url": "https://careers.ameriprise.com/search-jobs/r25_0000001832/investment-risk-manager-fixed-income-lead/", "company": "Columbia Threadneedle Investments"},
    {"url": "https://careers.ameriprise.com/search-jobs/r25_0000002230/operational-risk-manager/", "company": "Columbia Threadneedle Investments"},
    {"url": "https://careers.ameriprise.com/search-jobs/r25_0000003594/quantitative-portfolio-manager/", "company": "Columbia Threadneedle Investments"},
    {"url": "https://careers.ameriprise.com/search-jobs/r25_0000003816/senior-multi-asset-investment-risk-analyst/", "company": "Columbia Threadneedle Investments"},
    {"url": "https://careers.ameriprise.com/search-jobs/r26_0440/data-scientist/", "company": "Columbia Threadneedle Investments"},
    {"url": "https://careers.arag.co.uk/vacancies", "company": "ARAG"},
    {"url": "https://careers.atradius.com/en/ad/manager-of-analysts-credit-specialties/hbl9h1", "company": "Atradius"},
    {"url": "https://careers.auroraer.com/en/postings", "company": "Aurora Energy Research"},
    {"url": "https://careers.axa.com/global/en", "company": "AXA"},
    {"url": "https://careers.axa.com/jobs", "company": "AXA"},
    {"url": "https://careers.bankofireland.com/jobs", "company": "Bank of Ireland"},
    {"url": "https://careers.beazley.com/jobs", "company": "Beazley"},
    {"url": "https://careers.benefactgroup.com/jobs", "company": "Benefact Group"},
    {"url": "https://careers.british-business-bank.co.uk/en/postings", "company": "British Business Bank"},
    {"url": "https://careers.db.com/professionals/search-roles/", "company": "Deutsche Bank"},
    {"url": "https://careers.domesticandgeneral.com/", "company": "Domestic & General"},
    {"url": "https://careers.edfenergy.com/", "company": "EDF Energy"},
    {"url": "https://careers.enstargroup.com/search-our-jobs/job-details/4826329101/Quantitative_Risk_Analyst", "company": "Enstar"},
    {"url": "https://careers.enstargroup.com/vacancies", "company": "Enstar"},
    {"url": "https://careers.everywhen.co.uk/jobs", "company": "The Ardonagh Group"},
    {"url": "https://careers.fexco.com/vacancy", "company": "Fexco"},
    {"url": "https://careers.gic.com.sg/", "company": "GIC"},
    {"url": "https://careers.ice.com/jobs", "company": "ICE"},
    {"url": "https://careers.ing.com/en", "company": "ING Bank"},
    {"url": "https://careers.investec.co.uk/jobs", "company": "Investec"},
    {"url": "https://careers.isio.com/jobs", "company": "Isio"},
    {"url": "https://careers.jefferies.com/", "company": "Jefferies"},
    {"url": "https://careers.lancashiregroup.com/en/postings", "company": "Lancashire Group"},
    {"url": "https://careers.legalandgeneral.com/", "company": "Legal & General"},
    {"url": "https://careers.lightsourcebp.com/", "company": "Lightsource BP"},
    {"url": "https://careers.mizuhoemea.com/", "company": "Mizuho Financial Group"},
    {"url": "https://careers.moodys.com/associate-director-risk-management", "company": "Moody's"},
    {"url": "https://careers.moodys.com/avp-risk-management-third-party-risk-management", "company": "Moody's"},
    {"url": "https://careers.nfumutual.co.uk/jobs", "company": "NFU Mutual"},
    {"url": "https://careers.ovo.com/", "company": "Ovo Energy"},
    {"url": "https://careers.pageuppeople.com/728/cw/en", "company": "NewDay"},
    {"url": "https://careers.quintet.com/BrownShipley", "company": "Quintet"},
    {"url": "https://careers.securetrustbank.com/vacancies", "company": "Secure Trust Bank"},
    {"url": "https://careers.simplyhealth.co.uk/vacancies", "company": "Simplyhealth"},
    {"url": "https://careers.so.energy/jobs", "company": "So Energy"},
    {"url": "https://careers.societegenerale.com/en/job-offers/counterparty-credit-risk-officer-vp-25000O3E-en", "company": "Societe Generale"},
    {"url": "https://careers.societegenerale.com/en/job-offers/head-of-emerging-credit-trading-director-25000AKW-en", "company": "Societe Generale"},
    {"url": "https://careers.societegenerale.com/en/job-offers/hedge-funds-risk-analyst-associate-25000CJG-en", "company": "Societe Generale"},
    {"url": "https://careers.societegenerale.com/en/job-offers/infrastructure-finance-vp-250007OR-en", "company": "Societe Generale"},
    {"url": "https://careers.somersetbridgeinsurance.com/vacancies/2663/", "company": "Somerset Bridge Group"},
    {"url": "https://careers.sse.com/jobs", "company": "SSE"},
    {"url": "https://careers.successionwealth.co.uk/", "company": "Succession Wealth"},
    {"url": "https://careers.swissre.com/", "company": "Swiss Re"},
    {"url": "https://careers.thenottingham.com/vacancies", "company": "The Nottingham"},
    {"url": "https://careers.ukpowernetworks.co.uk/", "company": "UK Power Networks"},
    {"url": "https://careers.virginmoney.com/", "company": "Virgin Money"},
    {"url": "https://careers.vistra.com/", "company": "Vistra"},
    {"url": "https://careers.wesleyan.co.uk/vacancies", "company": "Wesleyan"},
    {"url": "https://careersemea.smbcgroup.com/", "company": "SMBC"},
    {"url": "https://careerssearch.saga.co.uk/jobs", "company": "Saga"},
    {"url": "https://careerstore.munichre.com/", "company": "Munich Re"},
    {"url": "https://carlyle.avature.net/externalcareers/ApplicationMethods", "company": "Carlyle"},
    {"url": "https://ccb.peoplehr.net/Pages/JobBoard/Opening.aspx", "company": "Cambridge & Counties Bank"},
    {"url": "https://ce0382li.webitrent.com/ce0382li_webrecruitment", "company": "XPS"},
    {"url": "https://cezanneondemand.intervieweb.it/marlboroughgroup/jobs", "company": "Marlborough"},
    {"url": "https://cfc.pinpointhq.com/en/postings", "company": "CFC"},
    {"url": "https://chetwood-bank.pinpointhq.com/en/postings", "company": "Chetwood Bank"},
    {"url": "https://closebrothers.current-vacancies.com/Jobs/Advert", "company": "Close Brothers"},
    {"url": "https://compregroup.pinpointhq.com/en/postings", "company": "Compre"},
    {"url": "https://covermore.elmotalent.com.au/careers/careers", "company": "Cover-More Group"},
    {"url": "https://cumberland.current-vacancies.com/Jobs/Advert", "company": "The Cumberland"},
    {"url": "https://dalriadacareers-3173.icims.com/jobs", "company": "Dalriada"},
    {"url": "https://davies.pinpointhq.com/en/postings", "company": "Davies"},
    {"url": "https://dbs.ciphr-irecruit.com/Applicants/vacancy/1323/Financial-Risk-Specialist", "company": "Dudley Building Society"},
    {"url": "https://dbs.ciphr-irecruit.com/Applicants/vacancy/1326/Senior-Credit-Risk-Analyst", "company": "Dudley Building Society"},
    {"url": "https://dbs.ciphr-irecruit.com/Applicants/vacancy/1337/Head-of-Lending", "company": "Dudley Building Society"},
    {"url": "https://developmentbank.wales/portfolio-executive-risk-and-restructuring", "company": "Development Bank of Wales"},
    {"url": "https://draxgroup.csod.com/ux/ats/careersite/11/home/requisition", "company": "Drax Group"},
    {"url": "https://ebs.peoplehr.net/Pages/JobBoard/Opening.aspx", "company": "Ecology Building Society"},
    {"url": "https://emea3.recruitmentplatform.com/syndicated/lay/jsoutputinitrapido.cfm", "company": "NFU Mutual"},
    {"url": "https://english-stonex.icims.com/jobs", "company": "StoneX"},
    {"url": "https://evolutionmoneyltd.livevacancies.co.uk/", "company": "Evolution Money"},
    {"url": "https://fscs.current-vacancies.com/Jobs/FeedLink", "company": "FSCS"},
    {"url": "https://furnessbuildingsociety.peoplehr.net/Pages/JobBoard/Opening.aspx", "company": "Furness Building Society"},
    {"url": "https://genre.csod.com/ux/ats/careersite/2/home/requisition", "company": "Faraday"},
    {"url": "https://ghanainternationalbank-1644937212.teamtailor.com/jobs", "company": "GHIB"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/bso-account-manager-associate-12mth-fixed-term-contract", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/credit-control-manager-client-finance-birmingham", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/credit-specialist", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/data-scientist-1", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/global-equities-cash-equities-quant-analyst-vice-president", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/gmqr-non-linear-credit-vice-president", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/ito-uk-opc-expert-risk-officer-vp", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/model-risk-governance-and-oversight-market-abuse-surveillance-vice-president", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/operational-risk-analyst-6", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/partner-risk-management-analyst", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/risk-and-control-manager", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/risk-manager-consumer-finance", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/risk-manager-partner-finance", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/risk-manager-partner-finance-1", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/senior-risk-analyst-6", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/senior-risk-analyst-risk-anticipation", "company": "BNP Paribas"},
    {"url": "https://group.bnpparibas/en/careers/job-offer/v-i-e-asset-risk-analyst-swindon-h-f-12-mois", "company": "BNP Paribas"},
    {"url": "https://hamilton.bamboohr.com/careers", "company": "Hamilton"},
    {"url": "https://hinckleyandrugby.teamtailor.com/jobs", "company": "Hinckley & Rugby Building Society"},
    {"url": "https://hodgebank.co.uk/careers/head-of-credit-risk1/", "company": "Hodge"},
    {"url": "https://hodgebank.co.uk/careers/property-risk-analyst/", "company": "Hodge"},
    {"url": "https://hodgebank.co.uk/careers/senior-credit-risk-manager/", "company": "Hodge"},
    {"url": "https://icbccareers.resourcesolutions.com/gold/iapply/index.cfm", "company": "ICBC Standard Bank"},
    {"url": "https://inigohr.my.salesforce-sites.com/Recruit/fRecruit__ApplyJob", "company": "Inigo"},
    {"url": "https://iqeq.com/careers/vacancies/client-advisory-manager-regulatory-compliance-2/", "company": "IQ-EQ"},
    {"url": "https://iqeq.com/careers/vacancies/head-of-risk-compliance/", "company": "IQ-EQ"},
    {"url": "https://iqeq.com/careers/vacancies/senior-officer-first-line-risk/", "company": "IQ-EQ"},
    {"url": "https://isw.changeworknow.co.uk/bii/vms/e/careers/positions/dsu2_jMIXmXBQAtS_IoLfw", "company": "British International Investment"},
    {"url": "https://isw.changeworknow.co.uk/principality/vms/e/careers/positions/a-bITRDgvknO2ZPS_UoEgv", "company": "Principality Building Society"},
    {"url": "https://isw.changeworknow.co.uk/principality/vms/e/careers/positions/aPNMmrPnjnizR-UgpSpKRO", "company": "Principality Building Society"},
    {"url": "https://isw.changeworknow.co.uk/principality/vms/e/careers/positions/cv5DF_r6Tn1yYX8p9HV-Oa", "company": "Principality Building Society"},
    {"url": "https://isw.changeworknow.co.uk/principality/vms/e/careers/positions/dWj-z4fBHdfA2vk927UNTQ", "company": "Principality Building Society"},
    {"url": "https://isw.changeworknow.co.uk/principality/vms/e/careers/positions/disVIGmynbnibdEI7_1H1A", "company": "Principality Building Society"},
    {"url": "https://jeragm.recruiterpal.com/career/jobs", "company": "JERA Global Markets"},
    {"url": "https://jobs.aib.ie/aib", "company": "Allied Irish Banks"},
    {"url": "https://jobs.amundi.com/offre-de-emploi/emploi-quantitative-analyst-fixed-income_98449.aspx", "company": "Amundi Asset Management"},
    {"url": "https://jobs.amundi.com/offre-de-emploi/emploi-risk-manager_108189.aspx", "company": "Amundi Asset Management"},
    {"url": "https://jobs.amundi.com/offre-de-emploi/emploi-senior-uk-risk-manager-emerging-markets_102686.aspx", "company": "Amundi Asset Management"},
    {"url": "https://jobs.amundi.com/offre-de-emploi/emploi-senior-uk-risk-manager-emerging-markets_105805.aspx", "company": "Amundi Asset Management"},
    {"url": "https://jobs.aspen.co/", "company": "Aspen Insurance"},
    {"url": "https://jobs.assurant.com/en/jobs", "company": "Assurant"},
    {"url": "https://jobs.ca-cib.com/offre-de-emploi/emploi-counterparty-risk-officer_109668.aspx", "company": "Credit Agricole"},
    {"url": "https://jobs.ca-cib.com/offre-de-emploi/emploi-credit-middle-office-associate_99402.aspx", "company": "Credit Agricole"},
    {"url": "https://jobs.ca-cib.com/offre-de-emploi/emploi-credit-risk-analyst_100389.aspx", "company": "Credit Agricole"},
    {"url": "https://jobs.ca-cib.com/offre-de-emploi/emploi-market-risk-analyst-_108796.aspx", "company": "Credit Agricole"},
    {"url": "https://jobs.ca-cib.com/offre-de-emploi/emploi-market-risk-analyst_100072.aspx", "company": "Credit Agricole"},
    {"url": "https://jobs.ca-cib.com/offre-de-emploi/emploi-xvaccr-quantitative-analyst_105227.aspx", "company": "Credit Agricole"},
    {"url": "https://jobs.canopius.com/en/sites/CX_1", "company": "Canopius"},
    {"url": "https://jobs.capitalone.co.uk/", "company": "Capital One"},
    {"url": "https://jobs.carfinance247.co.uk/vacancies", "company": "Carfinance 247"},
    {"url": "https://jobs.cfm.com/", "company": "CFM"},
    {"url": "https://jobs.citi.com/", "company": "Citi"},
    {"url": "https://jobs.dayforcehcm.com/en-US/loomissayles/CANDIDATEPORTAL/jobs", "company": "Loomis Sayles"},
    {"url": "https://jobs.dayforcehcm.com/en-US/stonefleming/CANDIDATEPORTAL/jobs", "company": "Stonehage Fleming"},
    {"url": "https://jobs.ebrd.com/", "company": "EBRD"},
    {"url": "https://jobs.ecotricity.co.uk/vacancies", "company": "Ecotricity"},
    {"url": "https://jobs.eni.com/it/sites/CX_1004", "company": "Eni"},
    {"url": "https://jobs.fidelisinsurance.com/Careers_Portal/JobDetail", "company": "Fidelis"},
    {"url": "https://jobs.fidelity.com/en/jobs", "company": "Fidelity Investments"},
    {"url": "https://jobs.halliburton.com/", "company": "Halliburton"},
    {"url": "https://jobs.hedgehoginsurance.com/jobs", "company": "Rostella"},
    {"url": "https://jobs.janushenderson.com/", "company": "Janus Henderson"},
    {"url": "https://jobs.jobvite.com/siriuspoint", "company": "SiriusPoint"},
    {"url": "https://jobs.lever.co/octoenergy", "company": "Octopus Energy"},
    {"url": "https://jobs.lever.co/simplybusiness", "company": "Simply Business"},
    {"url": "https://jobs.lever.co/titanwh", "company": "Titan"},
    {"url": "https://jobs.nationalgrid.com/UK", "company": "National Grid"},
    {"url": "https://jobs.nationalgrid.com/uk/jobs", "company": "National Grid"},
    {"url": "https://jobs.partnersgroup.com/", "company": "Partners Group"},
    {"url": "https://jobs.royallondon.com/", "company": "Royal London"},
    {"url": "https://jobs.scotiabank.com/", "company": "Scotiabank"},
    {"url": "https://jobs.standardchartered.com/", "company": "Standard Chartered"},
    {"url": "https://jobs.totalenergies.com/en_US/careers/JobDetail/Lead-Credit-Risk-Analyst", "company": "TotalEnergies"},
    {"url": "https://jobs.ubs.com/TGnewUI/Search/home/HomeWithPreLoad", "company": "UBS"},
    {"url": "https://jobsportal.lv.com/vacancies", "company": "LV="},
    {"url": "https://jtcgroup.csod.com/ux/ats/careersite/4/home/requisition", "company": "JTC Group"},
    {"url": "https://koch.avature.net/en_US/careers", "company": "Koch Industries"},
    {"url": "https://leekbs.peoplehr.net/Pages/JobBoard/Opening.aspx", "company": "Leek Building Society"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/GRS-Risk-Manager-Strategic-Stress-Scenario-Manager/19737", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/London-Data-Science-Manager/20186", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/London-UK-United-Kingdom-of-Great-Britain-and-Northern-Ireland-Credit-Analyst-Short-Term-Corporate-Receivables/19448", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/London-United-Kingdom-of-Great-Britain-and-Northern-Ireland-Analyst-I-II-Data-Science/19693", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/London-United-Kingdom-of-Great-Britain-and-Northern-Ireland-Catastrophe-Analyst/19715", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/London-United-Kingdom-of-Great-Britain-and-Northern-Ireland-Catastrophe-Analyst/19927", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/London-United-Kingdom-of-Great-Britain-and-Northern-Ireland-Senior-Risk-Analyst/19540", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/Senior-Catastrophe-Analyst/19743", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/Senior-Regulatory-Reporting-Accountant/19576", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LSMCareers/FolderDetail/Senior-Risk-Officer/19523", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LibertyCareers/FolderDetail/London-UK-United-Kingdom-of-Great-Britain-and-Northern-Ireland-LII-Property-Risk-Manager/20545", "company": "Liberty Specialty Markets"},
    {"url": "https://libertymutual1.avature.net/LibertyCareers/FolderDetail/Senior-Catastrophe-Analyst-Retail/19869", "company": "Liberty Specialty Markets"},
    {"url": "https://life-careers.com/canadalife", "company": "Irish Life Group"},
    {"url": "https://linde.csod.com/ux/ats/careersite/20/home/requisition", "company": "Linde"},
    {"url": "https://lockton-career.talent-soft.com/", "company": "Lockton"},
    {"url": "https://many-group.com/careers/opportunities/5553585004/", "company": "ManyGroup"},
    {"url": "https://many-group.com/careers/opportunities/5599966004/", "company": "ManyGroup"},
    {"url": "https://marex.breezy.hr/p/8c1d028f452201-product-control-associate", "company": "Marex"},
    {"url": "https://marex.breezy.hr/p/9656e0ac327e01-treasury-alm-analyst-vn2563", "company": "Marex"},
    {"url": "https://marex.breezy.hr/p/a472cd42bde201-change-and-transformation-risk-manager-vn2319", "company": "Marex"},
    {"url": "https://marex.breezy.hr/p/b52c4d5d162801-1st-line-risk-analyst", "company": "Marex"},
    {"url": "https://marex.breezy.hr/p/eed013a2f41601-credit-analyst", "company": "Marex"},
    {"url": "https://mhbs.co.uk/vacancies/", "company": "Market Harborough Building Society"},
    {"url": "https://monbs.current-vacancies.com/Jobs/Advert", "company": "Monmouthshire Building Society"},
    {"url": "https://monumentbanklimited.careers.hibob.com/jobs", "company": "Monument"},
    {"url": "https://motonovofinance.current-vacancies.com/Jobs/Advert", "company": "Aldermore Bank"},
    {"url": "https://my.corehr.com/pls/coreportal_tmmsp/erq_jobspec_version_4.display_form", "company": "Thomas Miller"},
    {"url": "https://my.corehr.com/pls/kmrecruit/erq_jobspec_version_4.display_form", "company": "Kensington"},
    {"url": "https://mycareers.yorkshirewater.com/", "company": "Yorkshire Water"},
    {"url": "https://mytalent.csod.com/ux/ats/careersite/2/home/requisition", "company": "Ageas"},
    {"url": "https://networkplus.pinpointhq.com/en/postings", "company": "Network Plus"},
    {"url": "https://northumbrianwater.current-vacancies.com/Jobs/Advert", "company": "Northumbrian Water Group"},
    {"url": "https://onefamily.current-vacancies.com/Jobs/Advert", "company": "OneFamily"},
    {"url": "https://peoplespartnership.my.salesforce-sites.com/recruit/fRecruit__ApplyJob", "company": "B&CE"},
    {"url": "https://poloworks.pinpointhq.com/en/postings", "company": "PoloWorks"},
    {"url": "https://portal.careers.hsbc.com/careers", "company": "HSBC"},
    {"url": "https://ppf.current-vacancies.com/Jobs/FeedLink", "company": "Pension Protection Fund"},
    {"url": "https://recruitment.macquarie.com/en_US/careers/JobDetail", "company": "Macquarie"},
    {"url": "https://recruitment.mo.co.uk/vacancies", "company": "Motability Operations"},
    {"url": "https://recrutement.bpce.fr/", "company": "Groupe BPCE"},
    {"url": "https://redmayne.current-vacancies.com/Jobs/Advert", "company": "Redmayne Bentley"},
    {"url": "https://saffronbuildingsociety.peoplehr.net/Pages/JobBoard/Opening.aspx", "company": "Saffron Building Society"},
    {"url": "https://schroders.referrals.selectminds.com/careers/jobs", "company": "Schroders"},
    {"url": "https://scottishfriendly.jobs.people-first.com/jobs", "company": "Scottish Friendly"},
    {"url": "https://sjp.csod.com/ux/ats/careersite/4/home/requisition", "company": "St James's Place"},
    {"url": "https://therightmortgage.co.uk/careers/", "company": "Right Mortgage"},
    # StoneX moved to ICIMS_BOARDS
    {"url": "https://ukcareers.hdi.global/Careers_Portal/JobDetail", "company": "HDI Global Specialty"},
    # Gallagher moved to ICIMS_BOARDS
    {"url": "https://uss.appellia.com/positions/Business-Manager---Risk--Compliance---Funding/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Credit-Analyst/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Enterprise-Risk-Manager/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Head-of-Funding-Strategy/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Investment-Control-Manager/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Investment-Risk-Associate/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Investment-Risk-Manager/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Operational-Risk-Manager/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Private-Markets-Strategy-Associate/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Private-Markets-Support---Private-Markets-Group--Credit---Property-/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Public-Markets-Operations-Associate---NAV-Control/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Senior-ALM-Risk-Associate/", "company": "USS"},
    {"url": "https://uss.appellia.com/positions/Senior-Quantitative-Model-Risk-Associate/", "company": "USS"},
    {"url": "https://utmosthr.my.salesforce-sites.com/recruit/fRecruit__ApplyJob", "company": "Utmost International"},
    {"url": "https://vacancies.somersetbridgegroup.com/en/postings", "company": "Somerset Bridge Group"},
    {"url": "https://vanquisbank.current-vacancies.com/Jobs/Advert", "company": "Vanquis Banking Group"},
    {"url": "https://wcgplc.bamboohr.com/careers", "company": "Walker Crips"},
    {"url": "https://www.admiraljobs.co.uk/", "company": "Admiral"},
    {"url": "https://www.affinitywatercareers.co.uk/jobs", "company": "Affinity Water"},
    {"url": "https://www.alanboswell.com/careers/risk-management-advisor-1/", "company": "Alan Boswell Group"},
    {"url": "https://www.allstate.jobs/", "company": "Allstate"},
    {"url": "https://www.atombank.co.uk/careers/risk/credit-risk-modelling-manager/", "company": "Atom Bank"},
    {"url": "https://www.atrium-uw.com/life-at-atrium/opportunities/vacancy/VA181", "company": "Atrium"},
    {"url": "https://www.atrium-uw.com/life-at-atrium/opportunities/vacancy/VA204", "company": "Atrium"},
    {"url": "https://www.aventumgroup.com/join-us/careers/vacancies/risk-analyst", "company": "Aventum"},
    {"url": "https://www.aventumgroup.com/join-us/careers/vacancies/risk-analyst-2", "company": "Aventum"},
    {"url": "https://www.bankoflondon.com/cw-careers/risk-manager---operations", "company": "Bank of London"},
    {"url": "https://www.bhspecialty.com/career/catastrophe-risk-analyst/", "company": "BHSI"},
    {"url": "https://www.bhspecialty.com/career/senior-risk-analyst/", "company": "BHSI"},
    {"url": "https://www.bordertocoast.org.uk/current-vacancies/", "company": "Border to Coast Pension Partnership"},
    {"url": "https://www.careers.severntrent.com/", "company": "Severn Trent"},
    {"url": "https://www.ccla.co.uk/careers/operational-risk-analyst-6-month-contract", "company": "CCLA"},
    {"url": "https://www.charitybank.org/careers/", "company": "Charity Bank"},
    {"url": "https://www.cloudonlinerecruitment.co.uk/bspokegroup/VacancyDetails.aspx", "company": "Bspoke Group"},
    {"url": "https://www.cls-group.com/people/your-career/jobs", "company": "CLS Group"},
    {"url": "https://www.co-operativebankjobs.co.uk/", "company": "Co-operative Bank"},
    {"url": "https://www.cornishmutual.co.uk/join-our-team/risk-management-advisor/", "company": "Cornish Mutual"},
    {"url": "https://www.directlinegroupcareers.com/", "company": "Direct Line"},
    {"url": "https://www.firstcentralcareers.com/jobs", "company": "First Central Insurance & Technology Group"},
    {"url": "https://www.hitachienergy.com/careers/open-jobs/details/JID3-159423", "company": "Hitachi Energy"},
    {"url": "https://www.janestreet.com/join-jane-street/position/8017833002/", "company": "Jane Street"},
    {"url": "https://www.janestreet.com/join-jane-street/position/8086895002/", "company": "Jane Street"},
    {"url": "https://www.janestreet.com/join-jane-street/position/8092053002/", "company": "Jane Street"},
    {"url": "https://www.janestreet.com/join-jane-street/position/8092062002/", "company": "Jane Street"},
    {"url": "https://www.janestreet.com/join-jane-street/position/8308920002/", "company": "Jane Street"},
    {"url": "https://www.jobtrain.co.uk/enwl/Job/JobDetail", "company": "Electricity North West"},
    {"url": "https://www.jobtrain.co.uk/transact/Job/JobDetail", "company": "Transact"},
    {"url": "https://www.jobtrain.co.uk/westbromcareers/Job/JobDetail", "company": "West Brom"},
    {"url": "https://www.jtcgroup.com/jobs", "company": "JTC Group"},
    {"url": "https://www.kkr.com/careers/career-opportunities/post", "company": "KKR"},
    {"url": "https://www.leedsbuildingsocietyjobs.co.uk/jobs", "company": "Leeds Building Society"},
    {"url": "https://www.liv-ex.com/data-scientist/", "company": "Liv-ex"},
    {"url": "https://www.localpensionspartnership.org.uk/Careers/Current-LPPI-opportunities", "company": "LPP"},
    {"url": "https://www.logicor.eu/en/eu/careers/job-vacancies/job-vacancies/head-of-liquidity-and-market-risk-uk", "company": "Logicor"},
    {"url": "https://www.logicor.eu/en/eu/careers/job-vacancies/job-vacancies/treasury-analyst-liquidity-and-market-risk-uk", "company": "Logicor"},
    {"url": "https://www.mako.com/opportunities/job-listing", "company": "Mako Group"},
    {"url": "https://www.marex.com/careers/career-opportunities/0709ce9e27f001-treasury-project-manager-ba/", "company": "Marex"},
    {"url": "https://www.marex.com/careers/career-opportunities/2d808cac08e101-risk-transformation-manager/", "company": "Marex"},
    {"url": "https://www.miller-insurance.com/careers/current-vacancies/treasury-analyst-finance/", "company": "Miller"},
    {"url": "https://www.monumentregroup.com/vacancy/credit-portfolio-management-associate/", "company": "Monument Re"},
    {"url": "https://www.nationwide-jobs.co.uk/jobs", "company": "Nationwide Building Society"},
    {"url": "https://www.ocorian.com/", "company": "Ocorian"},
    {"url": "https://www.oxam.com/portfolio/quantitative_researcher/", "company": "Oxford Asset Management"},
    {"url": "https://www.partnersand.com/resources/data-scientist/", "company": "Partners&"},
    {"url": "https://www.pepper-advantage.com/available-jobs", "company": "Pepper Advantage"},
    {"url": "https://www.pfgl.co.uk/careers/vacancies-jobs/", "company": "Perspective"},
    {"url": "https://www.premiermiton.com/wp-content/uploads/2025/07/2025.07_PMI-Job-Advert-Credit-Analyst.pdf", "company": "Premier Miton Investors"},
    {"url": "https://www.rsainsurance.co.uk/careers/uk-job-description/", "company": "RSA"},
    {"url": "https://www.rsml.co.uk/careers/vacancies/82a4c65b-92ff-4fa2-bfed-ae73e01d180d/", "company": "RiverStone"},
    {"url": "https://www.rsml.co.uk/careers/vacancies/88d28f34-3104-482c-973c-38cccac5288c/", "company": "RiverStone"},
    {"url": "https://www.seopa.com/careers/data-scientist/", "company": "Seopa"},
    {"url": "https://www.squarepoint-capital.com/open-opportunities", "company": "Squarepoint"},
    {"url": "https://www.swansea-bs.co.uk/cs/c/", "company": "Swansea Building Society"},
    {"url": "https://www.thetipton.co.uk/about-us/join-our-team/", "company": "Tipton & Coseley Building Society"},
    {"url": "https://www.timefinance.com/wp-content/uploads/2025/04/Job-specification-Recoveries-Risk-Manager-2025.pdf", "company": "Time Finance"},
    {"url": "https://www.triodos.co.uk/vacancies/120647/business-banking-risk-manager", "company": "Triodos Bank"},
    {"url": "https://www.triodos.co.uk/vacancies/121350/head-of-enterprise-financial-operational-risk", "company": "Triodos Bank"},
    {"url": "https://www.triodos.co.uk/vacancies/121359/financial-risk-senior-manager", "company": "Triodos Bank"},
    {"url": "https://www.ukfinance.org.uk/careers/director-unsecured-consumer-credit", "company": "UK Finance"},
    {"url": "https://www.unitedutilities.com/corporate/careers/details/", "company": "United Utilities Group"},
    {"url": "https://www.utbank.co.uk/grow-with-utb/job-role-template-54/", "company": "United Trust Bank"},
    {"url": "https://www.utbank.co.uk/grow-with-utb/operational-risk-analyst-operations/", "company": "United Trust Bank"},
    {"url": "https://www.utbank.co.uk/grow-with-utb/risk-analyst-risk-290925/", "company": "United Trust Bank"},
    {"url": "https://www.vidabank.co.uk/our-group/careers/current-opportunities/alm-risk-manager/", "company": "Vida Bank"},
    {"url": "https://www.werkenbijabnamro.nl/vacature/8861/information-operational-risk-officer", "company": "ABN AMRO"},
    {"url": "https://www.werkenbijabnamro.nl/vacature/9057/senior-risk-officer", "company": "ABN AMRO"},
    {"url": "https://www.workingatdllgroup.com/en/Vacancy", "company": "DLL"},
    {"url": "https://yourcareer.rathbones.com/", "company": "Rathbones"},
]

# ---------------------------------------------------------------------------
# Lever boards — public API, no auth required
# slug = company identifier used in api.lever.co/v0/postings/{slug}
# ---------------------------------------------------------------------------
LEVER_BOARDS: list[dict] = [
    # Only boards confirmed live on Lever API (others moved to Greenhouse — see above)
    {"company": "Plaid",  "slug": "plaid",  "url": "https://jobs.lever.co/plaid"},
]

# ---------------------------------------------------------------------------
# iCIMS boards — Playwright scraper (scrapers/icims.py)
# url = base career site URL (without query params)
# ---------------------------------------------------------------------------
ICIMS_BOARDS: list[dict] = [
    # UK / Europe (moved from GENERIC_BROWSER_BOARDS)
    {"company": "StoneX",          "slug": "uk-stonex",      "url": "https://uk-stonex.icims.com/jobs"},
    {"company": "Gallagher",       "slug": "ukjobs-ajg",     "url": "https://ukjobs-ajg.icims.com/jobs"},
    # US insurance & asset management
    {"company": "Ameriprise Financial",      "slug": "ameriprise",      "url": "https://careers-ameriprise.icims.com/jobs"},
    {"company": "Principal Financial Group", "slug": "principal",       "url": "https://careers-principal.icims.com/jobs"},
    {"company": "Unum Group",                "slug": "unum",            "url": "https://careers-unum.icims.com/jobs"},
    {"company": "Lincoln Financial",         "slug": "lfg",             "url": "https://careers-lfg.icims.com/jobs"},
    {"company": "New York Life",             "slug": "newyorklife",     "url": "https://careers-newyorklife.icims.com/jobs"},
    {"company": "Guardian Life",             "slug": "guardianlife",    "url": "https://careers-guardianlife.icims.com/jobs"},
    {"company": "Pacific Life",              "slug": "pacificlife",     "url": "https://careers-pacificlife.icims.com/jobs"},
    {"company": "Transamerica",              "slug": "transamerica",    "url": "https://careers-transamerica.icims.com/jobs"},
    {"company": "Protective Life",           "slug": "protective",      "url": "https://careers-protective.icims.com/jobs"},
    {"company": "Voya Financial",            "slug": "voya",            "url": "https://careers-voya.icims.com/jobs"},
    {"company": "OneAmerica",                "slug": "oneamerica",      "url": "https://careers-oneamerica.icims.com/jobs"},
]

# ---------------------------------------------------------------------------
# Search keywords (used by API scrapers that support server-side search)
# ---------------------------------------------------------------------------
SEARCH_TERMS = [
    "risk", "quant", "quantitative", "compliance", "strats", "pricing", "algorithmic",
    "audit", "legal", "cyber", "trader", "trading",
]
